Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2021-07, with the labels that each got.

#1409 [Comparison Chart] Update scale abbreviations, loading spinner
  src/app/components/FinanceV2Components/ComparisonChart/index.tsx
  src/app/components/FinanceV2Components/LootDrop/index.tsx
  src/app/components/Spinner/index.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/PoolChart.tsx
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/components/RowTable/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1381 Adds a hidden LocalSharedArrayBuffer component
  src/app/components/LocalSharedArrayBuffer/index.tsx
  src/app/pages/LiquidityMining/index.tsx
Labels: bug, enhancement

#1413 bug/1405-stake-button-main
  src/app/pages/BuySovPage/components/Features/StakeVote.tsx
Labels: bug

#1420 Remove unused workflow, add development_external branch sync workflow
  .github/workflows/codeql-analysis.yml
  .github/workflows/sync-development-external.yml
Labels: enhancement

#1423 [Comparison Chart] Improve label abbreviations
  src/app/components/FinanceV2Components/ComparisonChart/Chart.tsx
  src/app/components/FinanceV2Components/ComparisonChart/index.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/PoolChart.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/utils/helpers.ts
Labels: enhancement

#1427 Remove loot drop for DoC pool, update date for Lend promo
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/index.tsx
Labels: enhancement

#1428 Feat/loot drop release
  src/app/components/FinanceV2Components/ComparisonChart/Chart.tsx
  src/app/components/FinanceV2Components/ComparisonChart/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/utils/helpers.ts
Labels: release

#1431 add maintenance to lend v2.
  src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/index.tsx
  src/styles/sass/_custom-styles.scss
Labels: enhancement

#1433 [YieldFarm] - fixed 'unmounted components' errors
  src/app/hooks/useReserveWeight.ts
  src/app/pages/LiquidityMining/components/MiningPool/PoolAssetInfo.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
Labels: bug

#1412 Bug/1193 missing translations
  src/app/components/StakingDateSelector/index.tsx
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/StakeForm.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/pages/LiquidityMining/components/HistoryTable/TableRow/index.tsx
  src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
  src/locales/en/translation.json
  src/locales/i18n.ts
Labels: copy

#1443 Fix/amm address update for testnet
  src/utils/blockchain/contracts.testnet.ts
Labels: bug

#1440 bug/1403-history-yield
  src/app/components/FinanceV2Components/CardRow/index.tsx
  src/app/components/Skeleton/SkeletonRow.tsx
  src/app/containers/WalletPage/index.tsx
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/SpotTradingPage/index.tsx
Labels: bug

#1454 [useLending_balanceOf] Fix silent errors when retrieving pool balances
  src/app/hooks/lending/useLending_balanceOf.ts
Labels: bug

#1461 Updated MoC amm pool address for mainnet
  src/utils/blockchain/contracts.ts
Labels: enhancement

#1462 [Header] Update Sovryn logo
  src/app/components/Header/index.tsx
  src/assets/images/sovryn-logo-alpha.svg
Labels: enhancement

#1432 [Staking] - #1425 update staking history with a new endpoints
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/AccessCodeVerificationStep/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1401 Changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1468 bug/1403_history_yield
  src/app/components/Skeleton/SkeletonRow.tsx
  src/app/containers/SwapPage/Loadable.tsx
  src/app/containers/SwapPage/index.tsx
  src/app/pages/LendingPage/index.tsx
Labels: bug

#1476 Minor change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1439 Bug/1204 language detection
  package.json
  src/app/components/LanguageToggle/index.tsx
  src/locales/i18n.ts
  yarn.lock
Labels: bug

#1441 [Staking] - #1438 fixed rounding issue
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/index.tsx
Labels: bug

#1486 [Stake Page] Fix governance link
  src/app/containers/StakePage/index.tsx
Labels: bug

#1501 New string PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1509 Update recalibration date for Loot Drops
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/index.tsx
Labels: copy

#1521 Staging deployment workflow
  .github/workflows/deploy-staging.yml
  .github/workflows/stale.yml
  README.md
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/index.tsx
Labels: internal

#1507 Add localization strings
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/SwapFormContainer/components/SwapAssetSelector/index.tsx
  src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1505 [Lend Page] XUSD profit display fix
  src/app/hooks/lending/useLending_checkpointPrice.ts
  src/app/pages/LendingPage/components/CurrencyContainer/UserLendingInfo.tsx
Labels: bug

#1524 New string PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1527 [Stake History] Increase/extend stake translations
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
Labels: bug, copy

#1530 [Stake History] Localisation for "Loading" text
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: copy

#1531 Fix PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1429 Bug/1298 wrong update build id
  .env.local
  config/webpack.config.js
  package.json
  public/version.json
  scripts/build.js
  src/app/components/ServiceWorkerToaster/index.tsx
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/pt_br/translation.json
  yarn.lock
Labels: bug

#1534 [Portfolio] Fix Fish token mainnet issues
  src/app/components/UserAssets/FishDollarValue.tsx
  src/app/components/UserAssets/index.tsx
  src/utils/dictionaries/assets-dictionary.ts
Labels: bug

#1483 [Lend] - #1455
  src/app/components/Form/AmountInput/index.tsx
  src/app/hooks/lending/useLending_checkpointPrice.ts
  src/app/pages/LendingPage/components/CurrencyContainer/UserLendingInfo.tsx
  src/app/pages/LendingPage/components/LendingDialog/index.tsx
  src/utils/dictionaries/assets-dictionary.ts
  yarn.lock
Labels: bug, enhancement

#1522 Fix vested SOV delegating
  src/app/containers/StakePage/components/CurrentVests.tsx
  src/app/containers/StakePage/index.tsx
  src/app/hooks/staking/useVestingDelegate.ts
  src/store/global/transactions-store/types.ts
Labels: bug

#1542 Update Loot Drop recalibration dates
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/index.tsx
Labels: copy

#1543 [Stake] Update current vested asset header text
  src/locales/en/translation.json
Labels: bug, copy

#1547 [Lend] Add max deposit limit text
  src/app/pages/LendingPage/components/LendingDialog/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: bug

#1549 [Reward Page] Hide history if wallet not connected
  src/app/pages/RewardPage/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1551 Dev to release
  src/app/components/Header/index.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/UserLendingInfo.tsx
  src/app/pages/LendingPage/components/LendingDialog/index.tsx
  src/app/pages/RewardPage/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: release

#1475 Feat/wallet rework
  config/webpack.config.js
  package.json
  src/app/components/AddressBadge/index.tsx
  src/app/components/AssetWalletBalance/index.tsx
  src/app/components/LoanTokenGraphs/index.tsx
  src/app/components/NetworkRibbon/NetworkRibbon.tsx
  src/app/containers/ConnectWalletButton/index.tsx
  src/app/containers/FastBtcDialog/components/MainScreen.tsx
  src/app/containers/FastBtcDialog/components/TransackScreen.tsx
  src/app/containers/WalletConnector/index.tsx
  src/app/containers/WalletProvider/index.tsx
  src/app/containers/WalletProvider/slice.ts
  src/app/containers/WalletProvider/types.ts
  src/app/hooks/useCanInteract.ts
  src/app/pages/BridgeDepositPage/components/ChainSelector/index.tsx
  src/app/pages/BridgeDepositPage/components/ReturnToPortfolio/index.tsx
  src/app/pages/BridgeDepositPage/components/SidebarSteps/index.tsx
  src/app/pages/BridgeDepositPage/components/WalletSelector/index.tsx
  src/app/pages/BridgeDepositPage/index.tsx
  src/app/pages/BridgeDepositPage/saga.ts
  src/app/pages/BridgeDepositPage/types.ts
  src/app/pages/BridgeDepositPage/utils/bridge-network.ts
  src/app/pages/LendingPage/components/CurrencyContainer/PoolChart.tsx
  src/app/pages/MarginTradePage/components/EngageButton/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/EngageWalletStep/index.tsx
  src/app/pages/SpotTradingPage/components/EngageButton/index.tsx
  src/utils/sovryn/contract-writer.ts
  yarn.lock
Labels: do-not-merge!

#1552 Add new string PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1561 [Swap] - added footer
  src/app/containers/SwapPage/index.tsx
Labels: enhancement

#1510 Feat/1492 webpack optimization eslint and thread-loader
  .eslintrc.js
  config/webpack.config.js
  package.json
  src/app/hooks/useAnalytics.ts
  src/app/hooks/useCookie.ts
  src/locales/pt_br/translation.json
  yarn.lock
Labels: dependencies, enhancement

#1497 Align buttons in margin trade dialog
  src/app/components/Form/DialogButton/index.tsx
  src/app/components/NotificationForm/NotificationFormContainer/index.tsx
  src/app/components/OptOutDialog/index.tsx
  src/app/components/UserAssets/index.tsx
  src/app/components/UserAssets/useVestedStaking_balanceOf.ts
  src/app/pages/LendingPage/components/LendingDialog/index.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/AddLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/index.tsx
  src/app/pages/LiquidityMining/components/AmmPoolsBanner/PoolTransferDialog.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/RemoveLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/index.tsx
  src/app/pages/MarginTradePage/components/AddToMarginDialog/index.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
  src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
  src/styles/components.css
  src/styles/tailwindcss/components/inputs.css
Labels: bug

#1557 Change Vesting Schedule to Type
  src/locales/en/translation.json
Labels: copy

#1567 Removes dummy MOC lending contract
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
Labels: bug
