Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2021-05, with the labels that each got.

#1005 fastbtc maintenance
  package.json
  src/app/containers/FastBtcDialog/components/MainScreen.tsx
  src/app/containers/FastBtcDialog/components/TopUpHistory.tsx
  src/app/containers/FastBtcDialog/index.tsx
  yarn.lock
Labels: enhancement

#979 Help Desk button for ticketing system
  .env.local
  .env.mainnet.local
  .env.production
  .env.testnet
  public/index.html
Labels: enhancement

#1012 fixes lent amount withdrawals
  src/app/components/AssetWalletBalance/index.tsx
  src/app/containers/LendBorrowSovryn/LendingContainer/index.tsx
  src/app/containers/LendBorrowSovryn/components/ButtonGroup/index.tsx
  src/app/containers/LendBorrowSovryn/components/CurrencyContainer/CurrencyRow.tsx
Labels: bug

#1017 Fixes wrong reward pool endpoint
  src/app/containers/LiquidityMining/components/RewardPool.tsx
Labels: bug

#1025 Margin trading interface adjustments
  src/app/components/Helpers/index.tsx
  src/utils/dictionaries/trading-pair-dictionary.ts
Labels: enhancement

#1035 Fixes open positions liquidation price
  src/utils/display-text/format.ts
Labels: bug, release

#1009 Spot trading UI
  internals/generators/page/appendRootState.hbs
  internals/generators/page/importContainerState.hbs
  internals/generators/page/index.test.tsx.hbs
  internals/generators/page/index.ts
  internals/generators/page/index.tsx.hbs
  internals/generators/page/loadable.tsx.hbs
  internals/generators/page/saga.ts.hbs
  internals/generators/page/selectors.ts.hbs
  internals/generators/page/slice.ts.hbs
  internals/generators/page/types.ts.hbs
  internals/generators/plopfile.ts
  src/app/components/Form/RadioGroup/index.tsx
  src/app/components/Header/index.tsx
  src/app/containers/SpotHistory/index.tsx
  src/app/index.tsx
  src/app/pages/SpotTradingPage/Loadable.tsx
  src/app/pages/SpotTradingPage/components/Button/index.tsx
  src/app/pages/SpotTradingPage/components/BuySell/index.tsx
  src/app/pages/SpotTradingPage/components/EngageButton/index.tsx
  src/app/pages/SpotTradingPage/components/PriceHistory/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
  src/app/pages/SpotTradingPage/index.tsx
  src/app/pages/SpotTradingPage/saga.ts
  src/app/pages/SpotTradingPage/selectors.ts
  src/app/pages/SpotTradingPage/slice.ts
  src/app/pages/SpotTradingPage/types.ts
  src/locales/en/translation.json
  src/styles/components.css
  src/styles/tailwindcss/components/radio-button.css
  src/styles/tailwindcss/components/trade-btn.css
  src/types/RootState.ts
Labels: enhancement

#1026 New Swap UI adjustments
  src/app/components/AssetRenderer/index.module.css
  src/app/components/AssetRenderer/index.tsx
  src/app/components/AvailableBalance/index.tsx
  src/app/components/Form/AmountInput/index.tsx
  src/app/containers/SwapFormContainer/components/SwapAssetSelector/index.tsx
  src/app/containers/SwapFormContainer/components/SwapAssetSelector/styled.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/containers/SwapHistory/index.tsx
  src/app/containers/SwapPage/index.tsx
  src/app/pages/BuySovPage/components/Button/buy.tsx
  src/assets/images/swap/swap_horizontal.svg
  src/styles/sass/new-design.scss
  src/styles/tailwindcss/components/inputs.css
Labels: enhancement

#1031 Reward SOV (Vesting table)
  src/app/components/UserAssets/VestedAssets.tsx
  src/app/components/UserAssets/useVestedStaking_balanceOf.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
Labels: enhancement, release

#1074 Update circulating supply
  src/app/pages/BuySovPage/components/InfoBar/index.tsx
Labels: enhancement

#1050 Feat/redesign updates
  package.json
  src/app/components/ComparisonChart/index.tsx
  src/app/components/Header/index.tsx
  src/app/components/LoanTokenGraphs/index.tsx
  src/app/components/NotificationForm/NotificationFormContainer/index.tsx
  src/app/components/TradingChart/index.tsx
  src/app/containers/LendBorrowSovryn/components/CurrencyContainer/CurrencyRow.tsx
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/app/pages/MarginTradePage/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
  src/styles/tailwindcss/components/select.css
  yarn.lock
Labels: enhancement

#1085 Feat/559 upgrade chart
  .gitignore
  README.md
  bin/gh-pack
  package.json
  public/index.html
  scripts/build.js
  scripts/copy-chart-libs.js
  scripts/start.js
  src/app/components/TradingChart/datafeed.ts
  src/app/components/TradingChart/index.tsx
  src/app/components/TradingChart/streaming.ts
  src/app/components/UserAssets/VestedAssets.tsx
  src/app/pages/MarginTradePage/index.tsx
  src/app/pages/SpotTradingPage/components/BuySell/index.tsx
  src/app/pages/SpotTradingPage/index.tsx
  src/locales/pt_br/translation.json
  src/utils/dictionaries/trading-pair-dictionary.ts
  src/utils/kaktana-react-lightweight-charts/Chart.d.ts
  src/utils/kaktana-react-lightweight-charts/Chart.js
  yarn.lock
Labels: enhancement

#1109 Minor change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1113 Profit calculation bug fixes
  src/app/components/TradeProfit/index.tsx
  src/app/hooks/trading/useMarginTrade.ts
  src/app/hooks/useFetch.ts
  src/app/hooks/useSendContractTx.ts
  src/app/pages/BuySovPage/components/InfoBar/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/OpenPositionRow.tsx
  src/app/pages/MarginTradePage/components/TradingHistory/index.tsx
Labels: bug, release

#1107 Finance V2 shared components
  src/app/components/AssetRenderer/index.tsx
  src/app/components/AssetSymbolRenderer/index.module.css
  src/app/components/AssetSymbolRenderer/index.tsx
  src/app/components/FinanceV2Components/CardRow/index.tsx
  src/app/components/FinanceV2Components/CardRow/styled.ts
  src/app/components/FinanceV2Components/ComparisonChart/Chart.tsx
  src/app/components/FinanceV2Components/ComparisonChart/index.tsx
  src/app/components/FinanceV2Components/LootDrop/LootDropSectionWrapper/index.tsx
  src/app/components/FinanceV2Components/LootDrop/index.tsx
  src/app/components/FinanceV2Components/LootDrop/styled.ts
  src/app/components/FinanceV2Components/PieChart/index.tsx
  src/app/components/FinanceV2Components/PieChart/styled.ts
  src/app/components/FinanceV2Components/PieChart/utils/convertPercentageToDegrees.ts
  src/app/components/FinanceV2Components/RowTable/TableBody/index.tsx
  src/app/components/FinanceV2Components/RowTable/index.tsx
  src/app/components/FinanceV2Components/RowTable/styled.ts
  src/app/components/FinanceV2Components/TablePoolRenderer/index.tsx
  src/app/components/FinanceV2Components/TablePoolRenderer/styled.ts
  src/app/components/FinanceV2Components/TableTransactionStatus/index.tsx
  src/app/components/FinanceV2Components/TopInfo/TopInfoContent/index.tsx
  src/app/components/FinanceV2Components/TopInfo/TopInfoSectionWrapper/index.tsx
  src/app/components/FinanceV2Components/TopInfo/TopInfoTitle/index.tsx
  src/app/components/FinanceV2Components/TopInfo/TopInfoWrapper/index.tsx
  src/app/components/FinanceV2Components/utils/getAssetColor.ts
  src/app/components/Footer/index.tsx
  src/app/components/LoanTokenGraphs/index.tsx
  src/app/pages/LiquidityMining/components/HistoryTable/TableBody/index.tsx
  src/app/pages/LiquidityMining/components/HistoryTable/TableHeader/index.tsx
  src/app/pages/LiquidityMining/components/HistoryTable/TableRow/index.tsx
  src/app/pages/LiquidityMining/components/HistoryTable/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/PoolChart.tsx
  src/app/pages/LiquidityMining/components/MiningPool/UserPoolInfo.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/components/RowTable/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/locales/en/translation.json
  tailwind.config.js
Labels: enhancement

#1123 Chart refresh on window focus
  src/app/components/TradingChart/streaming.ts
Labels: enhancement

#1122 Feat/1091 tracking optout
  src/app/components/Footer/index.tsx
  src/app/components/OptOutDialog/index.tsx
  src/app/hooks/useCookie.ts
  src/app/hooks/usePageViews.ts
  src/locales/en/translation.json
  src/utils/classifiers.ts
Labels: enhancement

#1128 bug/1126_double_border
  src/app/components/NetworkRibbon/_networkRibbon.scss
  src/app/components/NetworkRibbon/component/DetectionScreen.tsx
  src/app/containers/FastBtcDialog/components/FiatButton.tsx
Labels: bug

#1151 Restyle updates
  src/app/components/Arrows/ArrowDown.tsx
  src/app/components/ComparisonChart/index.tsx
  src/app/components/FinanceV2Components/LootDrop/index.tsx
  src/app/components/FinanceV2Components/LootDrop/styled.ts
  src/app/components/Footer/index.tsx
  src/app/components/Form/AmountInput/index.tsx
  src/app/components/MobileBrowsersWarningDialog/index.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/AddLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/PoolAssetInfo.tsx
  src/app/pages/LiquidityMining/components/MiningPool/PoolChart.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/RemoveLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/MarginTradePage/components/TxFeeCalculator/index.tsx
  src/app/pages/RewardPage/components/ClaimForm/index.tsx
  src/locales/en/translation.json
  src/styles/tailwindcss/components/form-group.css
  src/styles/tailwindcss/components/slider.css
  tailwind.config.js
Labels: enhancement

#1175 added eths token to portfolio
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/assets-dictionary.ts
Labels: release

#1160 [Stats Page] Update RBTC naming, error handling when no data
  src/app/containers/StatsPage/components/AmmBalance.tsx
  src/app/containers/StatsPage/components/TVL.tsx
Labels: copy

#1183 Translation strings. Closes #1068, closes #721
  src/app/containers/SpotHistory/index.tsx
  src/app/containers/SwapHistory/index.tsx
  src/app/pages/RewardPage/components/RewardHistory/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: copy

#1189 fixes predicted side token amount when adding liquidity to v1 pool
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/AddLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/hooks/useLiquidityMining_getExpectedV1PoolTokens.ts
  src/app/pages/LiquidityMining/hooks/useLiquidityMining_getExpectedV1TokenAmount.ts
Labels: bug, release

#1164 [Liquidity-Mining] Revert incorrect Asset label
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/index.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/index.tsx
  src/locales/en/translation.json
Labels: bug, copy
