Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2021-03, with the labels that each got.

#425 fast btc rework #418
  package.json
  src/app/components/Form/AddressQrCode/index.module.css
  src/app/components/Form/AddressQrCode/index.tsx
  src/app/components/TopUpHint/index.tsx
  src/app/components/UserAssets/index.tsx
  src/app/containers/FastBtcDialog/components/AddressButton.tsx
  src/app/containers/FastBtcDialog/components/MainScreen.tsx
  src/app/containers/FastBtcDialog/components/TopUpHistory.tsx
  src/app/containers/FastBtcDialog/components/TransactionScreen.tsx
  src/app/containers/FastBtcDialog/components/transaction.module.css
  src/app/containers/FastBtcDialog/index.module.css
  src/app/containers/FastBtcDialog/index.tsx
  src/app/containers/FastBtcDialog/saga.ts
  src/app/containers/FastBtcDialog/selectors.ts
  src/app/containers/FastBtcDialog/slice.ts
  src/app/containers/FastBtcDialog/types.ts
  src/app/containers/WalletPage/index.tsx
  src/locales/en/translation.json
  src/types/RootState.ts
  src/utils/toaster.ts
  yarn.lock
Labels: enhancement

#408 Feat/395 redeem origin sov
  package.json
  src/app/components/Button/index.module.css
  src/app/components/Button/index.tsx
  src/app/components/Form/AddressQrCode/index.module.css
  src/app/components/Form/AddressQrCode/index.tsx
  src/app/components/TopUpHint/index.tsx
  src/app/components/UserAssets/index.tsx
  src/app/components/UserAssets/useVestedStaking_balanceOf.ts
  src/app/containers/FastBtcDialog/components/AddressButton.tsx
  src/app/containers/FastBtcDialog/components/MainScreen.tsx
  src/app/containers/FastBtcDialog/components/TopUpHistory.tsx
  src/app/containers/FastBtcDialog/components/TransactionScreen.tsx
  src/app/containers/FastBtcDialog/components/transaction.module.css
  src/app/containers/FastBtcDialog/index.module.css
  src/app/containers/FastBtcDialog/index.tsx
  src/app/containers/FastBtcDialog/saga.ts
  src/app/containers/FastBtcDialog/selectors.ts
  src/app/containers/FastBtcDialog/slice.ts
  src/app/containers/FastBtcDialog/types.ts
  src/app/containers/WalletPage/components/OriginClaimBanner.tsx
  src/app/containers/WalletPage/components/OriginClaimDialog.tsx
  src/app/containers/WalletPage/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  src/store/global/transactions-store/types.ts
  src/types/RootState.ts
  src/utils/blockchain/abi/OriginInvestorsClaim.json
  src/utils/blockchain/abi/VestingRegistryOrigin.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
  src/utils/toaster.ts
  yarn.lock
Labels: enhancement

#454 Update doc links with new wiki. Closes #453
  src/app/components/Footer/index.tsx
  src/app/components/Header/index.tsx
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement

#379 Feat/335 - New Swap UI
  package.json
  src/app/containers/SwapFormContainer/components/SwapAmountField/Loadable.tsx
  src/app/containers/SwapFormContainer/components/SwapAmountField/index.tsx
  src/app/containers/SwapFormContainer/components/SwapAssetSelector/Loadable.tsx
  src/app/containers/SwapFormContainer/components/SwapAssetSelector/index.tsx
  src/app/containers/SwapFormContainer/components/SwapAssetSelector/styled.tsx
  src/app/containers/SwapFormContainer/components/SwapInputField/index.tsx
  src/app/containers/SwapFormContainer/components/SwapInputField/styled.tsx
  src/app/containers/SwapFormContainer/components/SwapSlippageModal/index.module.scss
  src/app/containers/SwapFormContainer/components/SwapSlippageModal/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/containers/SwapHistoryTable/constants.tsx
  src/app/containers/SwapHistoryTable/index.tsx
  src/app/containers/SwapPage/Loadable.tsx
  src/app/containers/SwapPage/index.tsx
  src/app/index.tsx
  src/assets/images/swap/ic_arrow_down.svg
  src/assets/images/swap/ic_setting.png
  src/assets/images/swap/ic_setting.svg
  src/assets/images/swap/ic_swap.svg
  src/index.tsx
  src/locales/en/translation.json
  src/styles/sass/new-design.scss
  yarn.lock
Labels: enhancement

#478 Feat/460 light charts
  package.json
  src/app/components/TradingChart/index.tsx
  src/app/components/TradingViewChart/index.tsx
  src/app/containers/TradingPage/index.tsx
  src/utils/dictionaries/trading-pair-dictionary.ts
  src/utils/kaktana-react-lightweight-charts/Chart.d.ts
  src/utils/kaktana-react-lightweight-charts/Chart.js
  yarn.lock
Labels: enhancement

#484 Implement Swap Form switch assets button for #450
  src/app/containers/SwapTradeForm/index.tsx
  src/locales/en/translation.json
Labels: bug, enhancement

#486 Feat/chart styling
  src/app/components/Header/index.tsx
  src/app/components/TradingChart/index.tsx
Labels: enhancement

#487 New FastBTCDialog translation strings for #457
  src/app/containers/FastBtcDialog/components/TransactionScreen.tsx
  src/locales/en/translation.json
Labels: enhancement

#497 Disable repay position button when low liquidity. Closes #474
  src/app/containers/CloseTradingPositionHandler/index.tsx
Labels: bug

#496 Feat/show arbitrage opportunity
  src/app/containers/SwapTradeForm/components/arbitrage.tsx
  src/app/containers/SwapTradeForm/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#499 Add new strings and translate to PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#503 Release
  CHANGELOG.md
  README.md
  bin/changelog
  package.json
  src/app/components/Header/index.tsx
  src/app/containers/SwapTradeForm/components/arbitrage.tsx
  src/app/containers/SwapTradeForm/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: release

#508 Makes sure dapp doesn't crash when backend returns faulty graph data
  src/app/components/TradingChart/index.tsx
  src/index.tsx
Labels: bug

#518 bug/512-remove0
  src/app/containers/FastBtcDialog/components/MainScreen.tsx
  src/app/containers/FastBtcDialog/index.module.css
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement

#536 Refresh chart every 15s
  src/app/components/TradingChart/index.tsx
Labels: bug

#543 unvest in website
  src/app/components/AssetWalletBalance/index.tsx
  src/app/components/TokenWalletBalance/index.tsx
  src/app/components/UserAssets/VestedAssets.tsx
  src/app/components/UserAssets/VestingDialog.tsx
  src/app/containers/SwapTradeForm/components/arbitrage.tsx
  src/app/hooks/staking/useGetUnlockedVesting.ts
  src/app/hooks/useAccount.ts
  src/app/hooks/useSendToContractAddressTx.ts
  src/locales/en/translation.json
  src/store/global/transactions-store/types.ts
  src/utils/sovryn/contract-reader.ts
  src/utils/sovryn/contract-writer.ts
Labels: enhancement

#533 Feat/501 asset refactor
  src/app/components/HintDialog/index.tsx
  src/app/components/UserAssets/index.tsx
  src/app/containers/CloseTradingPositionHandler/index.tsx
  src/app/containers/EngageWalletDialog/component/screen4/index.tsx
  src/app/containers/EngageWalletDialog/componentMobile/screen3/index.tsx
  src/app/containers/FastBtcDialog/components/TopUpHistory.tsx
  src/app/containers/LendBorrowSovryn/slice.ts
  src/app/containers/SalesPage/hooks/useSaleCalculator.ts
  src/app/containers/SwapTradeForm/components/arbitrage.tsx
  src/app/containers/SwapTradeForm/index.tsx
  src/app/containers/TradingHistory/index.tsx
  src/app/hooks/amm/useAddLiquidity.ts
  src/app/hooks/amm/useApproveAndAddLiquidity.ts
  src/app/hooks/amm/useApproveAndRemoveLiquidity.ts
  src/app/hooks/amm/useRemoveLiquidity.ts
  src/app/hooks/lending/useLending_approveAndLend.ts
  src/app/hooks/lending/useLending_approveAndUnlend.ts
  src/app/hooks/lending/useLending_burn.ts
  src/app/hooks/lending/useLending_mint.ts
  src/app/hooks/swap-network/useSwapNetwork_approveAndConvertByPath.ts
  src/app/hooks/swap-network/useSwapNetwork_convertByPath.ts
  src/app/hooks/trading/useApproveAndAndMargin.ts
  src/app/hooks/trading/useApproveAndBorrow.ts
  src/app/hooks/trading/useApproveAndCloseWithDeposit.ts
  src/app/hooks/trading/useApproveAndTrade.ts
  src/app/hooks/trading/useBorrow.ts
  src/app/hooks/trading/useCheckLiquidity.ts
  src/app/hooks/trading/useCloseWithDeposit.ts
  src/app/hooks/trading/useDepositCollateral.ts
  src/app/hooks/useAssetBalanceOf.ts
  src/locales/pt_br/translation.json
  src/types/asset.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/dictionaries/lending-pool-dictionary.ts
  src/utils/dictionaries/liquidity-pool-dictionary.ts
  src/utils/dictionaries/trading-pair-dictionary.ts
  src/utils/helpers.ts
Labels: enhancement

#481 Add fiat onramp
  .env.example
  .env.local
  .env.mainnet.local
  .env.production
  .env.testnet
  package.json
  src/app/components/Button/index.stories.tsx
  src/app/containers/FastBtcDialog/components/BTCButton.tsx
  src/app/containers/FastBtcDialog/components/FiatButton.tsx
  src/app/containers/FastBtcDialog/components/FiatDialogScreen.tsx
  src/app/containers/FastBtcDialog/components/MainScreen.tsx
  src/app/containers/FastBtcDialog/components/transak.tsx
  src/app/containers/FastBtcDialog/index.module.css
  src/app/containers/FastBtcDialog/index.tsx
  src/app/containers/FastBtcDialog/slice.ts
  src/app/containers/FastBtcDialog/types.ts
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/pt_br/translation.json
  yarn.lock
Labels: enhancement, next

#556 New copy for whitelist notification
  src/app/components/WhitelistedNotification/index.tsx
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/pt_br/translation.json
Labels: copy, enhancement
