Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2021-08, with the labels that each got.

#1585 August 2 updates
  src/app/components/UserAssets/useVestedStaking_balanceOf.ts
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/index.tsx
Labels: enhancement

#1586 Upgraded wallet version
  .env.example
  package.json
  src/app/containers/WalletProvider/index.tsx
  yarn.lock
Labels: internal

#1590 fix Arbitrage list issue.
  src/app/components/Arbitrage/Arbitrage.tsx
  src/utils/helpers.ts
Labels: bug

#1594 Release august 9
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/components/WithdrawVesting.tsx
  src/app/containers/VestedHistory/index.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/UserLendingInfo.tsx
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/hooks/useLiquidityMining_getPoolId.ts
  src/app/pages/LiquidityMining/hooks/useLiquidityMining_getUserInfoList.ts
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/SpotTradingPage/index.tsx
  src/locales/en/translation.json
Labels: release

#1569 Feat/1494 replace moment
  config/webpack.config.js
  package.json
  src/app/components/StakingDateSelector/index.tsx
  src/app/components/TradingChart/index.tsx
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/ExtendStakeForm.tsx
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/components/WithdrawConfimationForm.tsx
  src/app/containers/VestedHistory/index.tsx
  src/app/pages/Escrow/components/InfoBar/index.tsx
  src/app/pages/Escrow/components/PoolTable/index.tsx
  src/index.tsx
  src/locales/dayjs.ts
  src/locales/i18n.ts
  yarn.lock
Labels: dependencies

#1600 Disable claim button on reward SOV when tx is in progress
  src/app/pages/RewardPage/components/ClaimForm/index.tsx
  yarn.lock
Labels: bug

#1578 Remove eslint-disable comments
  src/app/components/ActiveBorrowTable/index.tsx
  src/app/components/ComparisonChart/index.tsx
  src/app/components/Dialogs/TxDialog.tsx
  src/app/components/FinanceV2Components/ComparisonChart/Chart.tsx
  src/app/components/MobileBrowsersWarningDialog/index.tsx
  src/app/components/NetworkDialog/index.module.css
  src/app/components/NetworkDialog/index.tsx
  src/app/components/NetworkRibbon/NetworkRibbon.tsx
  src/app/components/NetworkRibbon/_networkRibbon.scss
  src/app/components/NetworkRibbon/component/DetectionScreen.tsx
  src/app/components/OptOutDialog/index.tsx
  src/app/components/TradingChart/index.tsx
  src/app/components/UserAssets/TxDialog/index.tsx
  src/app/containers/ActiveUserBorrows/index.tsx
  src/app/containers/EmailPage/index.tsx
  src/app/containers/FastBtcDialog/components/MainScreen.tsx
  src/app/containers/FastBtcDialog/components/TransackScreen.tsx
  src/app/containers/FastBtcDialog/components/transak.tsx
  src/app/containers/FastBtcForm/saga.ts
  src/app/containers/SpotHistory/index.tsx
  src/app/containers/StakePage/components/WithdrawVesting.tsx
  src/app/containers/StatsPage/components/AmmBalance.tsx
  src/app/containers/StatsPage/components/TVL.tsx
  src/app/containers/StatsPage/components/TradingVolume.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/containers/SwapHistory/index.tsx
  src/app/containers/WalletProvider/index.tsx
  src/app/hooks/amm/usePoolToken.ts
  src/app/hooks/swap-network/useSwapNetwork_resolveRate.ts
  src/app/hooks/trading/useBorrowInterestRate.ts
  src/app/hooks/trading/useTrading_totalDeposit.ts
  src/app/hooks/useAnalytics.ts
  src/app/hooks/useGetContractPastEvents.ts
  src/app/hooks/useInterval.ts
  src/app/hooks/useTradeHistoryRetry.ts
  src/app/pages/BorrowPage/BorrowingContainer/index.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/UserLendingInfo.tsx
  src/app/pages/LendingPage/components/HistoryTable/index.tsx
  src/app/pages/LiquidityMining/components/HistoryTable/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/PoolChart.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/index.tsx
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/UpcomingSalesCard/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/BuyStep/components/BuyDialog/components/TxDialog/index.tsx
  src/app/pages/RewardPage/components/HistoryTable/index.tsx
  src/app/pages/SpotTradingPage/components/PriceHistory/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1570 Feat/1496 ban ts ignore
  .eslintrc.js
  .vscode/settings.json
  package.json
  src/app/hooks/trading/useGetLoan.ts
  src/utils/sovryn/contract-writer.ts
  src/utils/sovryn/sovryn-network.ts
  yarn.lock
Labels: enhancement

#1601 Updated supported browsers
  README.md
  package.json
Labels: enhancement

#1608 Automatically update recalibration dates
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/utils/dateHelpers.ts
Labels: enhancement

#1599 Show connected user wallet address in babelfish flows
  src/app/components/LinkToExplorer/index.tsx
  src/app/pages/BridgeDepositPage/components/AmountSelector/index.tsx
  src/app/pages/BridgeDepositPage/components/ConfirmStep/index.tsx
  src/app/pages/BridgeDepositPage/components/UserWallet/index.tsx
  src/app/pages/BridgeDepositPage/components/WalletSelector/index.tsx
  src/app/pages/BridgeDepositPage/dictionaries/assets/rsk-to-eth.mainnet.ts
  src/app/pages/BridgeDepositPage/dictionaries/assets/rsk-to-eth.testnet.ts
  src/app/pages/BridgeDepositPage/index.tsx
  src/app/pages/BridgeWithdrawPage/components/AmountSelector/index.tsx
  src/app/pages/BridgeWithdrawPage/components/TokenSelector/TokenItem.tsx
  src/app/pages/BridgeWithdrawPage/index.tsx
  src/locales/en/translation.json
  src/utils/classifiers.ts
  src/utils/metamaskHelpers.ts
Labels: enhancement

#1620 fix for max staking date
  src/app/components/StakingDateSelector/index.tsx
  src/app/containers/StakePage/components/IncreaseStakeForm.tsx
  src/app/containers/StakePage/components/StakeForm.tsx
  src/app/hooks/staking/useStakeIncrease.ts
  src/app/hooks/staking/useStakeStake.ts
Labels: bug

#1623 [Portfolio VestedAssets] Fix undefined Fish token
  src/app/components/UserAssets/useVestedStaking_balanceOf.ts
Labels: bug

#1637 [webpack] add type attribute to link tags to fix issue with brave
  config/webpack.config.js
  package.json
  public/index.html
  public/maintenance.html
  yarn.lock
Labels: bug, dependencies

#1636 [Staking] - fixed issues with max dates
  src/app/components/StakingDateSelector/index.tsx
  src/app/hooks/staking/useStakeExtend.ts
  src/app/hooks/staking/useStakeWithdraw.ts
Labels: bug

#1640 Feat/market cap landing
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/app/pages/LandingPage/components/CryptocurrencyPrices/types.tsx
  src/app/pages/LandingPage/components/TotalValueLocked/index.tsx
  src/app/pages/LandingPage/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1581 Add and translate new strings to PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1642 Date fixes to master
  src/app/components/Header/index.tsx
  src/app/components/StakingDateSelector/index.tsx
  src/app/components/UserAssets/VestingDialog.tsx
  src/app/components/UserAssets/index.tsx
  src/app/components/UserAssets/useVestedStaking_balanceOf.ts
  src/app/containers/StakePage/components/CurrentVests.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/VestedHistory/index.tsx
  src/app/hooks/staking/useStakeExtend.ts
  src/app/hooks/staking/useStakeWithdraw.ts
  src/app/index.tsx
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/app/pages/LandingPage/components/CryptocurrencyPrices/types.tsx
  src/app/pages/LandingPage/components/TotalValueLocked/index.tsx
  src/app/pages/LandingPage/index.tsx
  src/app/pages/OriginsClaimPage/Loadable.tsx
  src/app/pages/OriginsClaimPage/components/ClaimForm/index.tsx
  src/app/pages/OriginsClaimPage/index.tsx
  src/app/pages/OriginsLaunchpad/hooks/useGetActiveSaleTierId.ts
  src/app/pages/OriginsLaunchpad/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/AccessCodeVerificationStep/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/BuyStep/components/BuyDialog/components/BuySection/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/BuyStep/components/BuyDialog/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/BuyStep/components/Instructions/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/BuyStep/components/Instructions/styled.ts
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/BuyStep/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/ImportantInformationStep/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  src/store/global/transactions-store/types.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/assets-dictionary.ts
Labels: release

#1632 Fix vested SOV withdraw
  src/app/components/UserAssets/VestingDialog.tsx
Labels: bug

#1641 [Portfolio Vested History] Fix dayjs issue
  src/app/containers/VestedHistory/index.tsx
Labels: bug

#1668 Mainnet FISH amm pool
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/dictionaries/liquidity-pool-dictionary.ts
Labels: enhancement, release

#1671 Upgraded Amm v1 pools
  .github/workflows/deploy-staging.yml
  src/app/hooks/useMaintenance.ts
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/app/pages/LandingPage/components/TradingVolume/index.tsx
  src/store/global/maintenance-store/saga.ts
  src/utils/blockchain/contracts.ts
  src/utils/blockchain/gas-price.ts
  src/utils/dictionaries/liquidity-pool-dictionary.ts
  src/utils/sovryn/sovryn-network.ts
Labels: enhancement, release

#1672 [Storybook] update dependencies and eslints settings for storybook
  .eslintrc.js
  package.json
  yarn.lock
Labels: bug, dependencies

#1667 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1677 Storybook deployment to testnet server
  .env.testnet
  package.json
  yarn.lock
Labels: internal
