Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2021-04, with the labels that each got.

#532 Sov liquidity pool
  src/app/components/BorrowLiquidationPrice/index.tsx
  src/app/components/TradingPositionSelector/index.tsx
  src/app/components/UserAssets/VestedAssets.tsx
  src/app/components/UserAssets/index.tsx
  src/app/containers/LiquidityAddContainer/BalanceV1.tsx
  src/app/containers/LiquidityAddContainer/ExpectedPoolTokensV1.tsx
  src/app/containers/LiquidityAddContainer/PoolV1.tsx
  src/app/containers/LiquidityAddContainer/index.tsx
  src/app/containers/LiquidityRemoveContainer/RemovePoolV1.tsx
  src/app/containers/LiquidityRemoveContainer/index.tsx
  src/app/containers/MarginTradeForm/index.tsx
  src/app/hooks/amm/useAddV1Liquidity.ts
  src/app/hooks/amm/useApproveAndAddV1Liquidity.ts
  src/app/hooks/amm/useApproveAndRemoveV1Liquidity.ts
  src/app/hooks/amm/usePoolToken.ts
  src/app/hooks/amm/useRemoveV1Liquidity.ts
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/hooks/swap-network/useSwapNetwork_resolveRate.ts
  src/app/hooks/trading/useCachedAssetPrice.ts
  src/locales/en/translation.json
  src/styles/sass/new-design.scss
  src/types/asset.ts
  src/utils/blockchain/abi/LiquidityPoolV1Converter.json
  src/utils/blockchain/abi/RBTCWrapperProxy.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/dictionaries/lending-pool-dictionary.ts
  src/utils/dictionaries/liquidity-pool-dictionary.ts
  src/utils/dictionaries/trading-pair-dictionary.ts
  src/utils/models/liquidity-pool.ts
Labels: enhancement

#582 Feat/liquidity mining
  src/app/containers/LiquidityMining/components/PoolData.tsx
  src/app/containers/LiquidityMining/index.tsx
Labels: enhancement

#580 bug/565-statepage-strings
  src/app/containers/StatsPage/components/AmmBalance.tsx
  src/app/containers/StatsPage/components/TVL.tsx
  src/app/containers/StatsPage/components/TradingVolume.tsx
  src/app/containers/StatsPage/index.tsx
  src/locales/en/translation.json
Labels: copy, enhancement

#579 bug/558-fastbtc-buttons
  src/app/containers/FastBtcDialog/components/BTCButton.tsx
  src/app/containers/FastBtcDialog/components/FiatButton.tsx
  src/styles/sass/new-design.scss
Labels: bug

#574 New strings and translate to PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#594 Add new strings and translate to PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#550 Reworked wallet connection
  .env.local
  package.json
  src/app/components/AssetWalletBalance/index.tsx
  src/app/components/NetworkRibbon.tsx
  src/app/containers/ConnectWalletButton/index.tsx
  src/app/containers/ConnectWalletButton/saga.ts
  src/app/containers/EngageWalletDialog/Loadable.tsx
  src/app/containers/EngageWalletDialog/component/BrowserWallets/index.tsx
  src/app/containers/EngageWalletDialog/component/index.tsx
  src/app/containers/EngageWalletDialog/component/screen1/index.tsx
  src/app/containers/EngageWalletDialog/component/screen2/index.tsx
  src/app/containers/EngageWalletDialog/component/screen3/index.tsx
  src/app/containers/EngageWalletDialog/component/screen4/index.tsx
  src/app/containers/EngageWalletDialog/componentMobile/index.tsx
  src/app/containers/EngageWalletDialog/componentMobile/screen1/index.tsx
  src/app/containers/EngageWalletDialog/componentMobile/screen2/index.tsx
  src/app/containers/EngageWalletDialog/componentMobile/screen3/index.tsx
  src/app/containers/EngageWalletDialog/index.tsx
  src/app/containers/EngageWalletDialog/mobileNotReady/index.tsx
  src/app/containers/EngageWalletDialog/selectors.ts
  src/app/containers/EngageWalletDialog/slice.ts
  src/app/containers/EngageWalletDialog/types.ts
  src/app/containers/SalesPage/screen1/index.tsx
  src/app/containers/SandboxPage/index.tsx
  src/app/containers/WalletConnector/index.tsx
  src/app/containers/WalletProvider/index.tsx
  src/app/containers/WalletProvider/selectors.ts
  src/app/hooks/app/useAppTheme.ts
  src/app/hooks/useAccount.ts
  src/app/hooks/useBalance.ts
  src/app/hooks/useCanInteract.ts
  src/app/hooks/useSendToContractAddressTx.ts
  src/app/index.tsx
  src/index.tsx
  src/types/RootState.ts
  src/utils/sovryn/contract-reader.ts
  src/utils/sovryn/contract-writer.ts
  src/utils/sovryn/sovryn-network.ts
  vercel.json
  yarn.lock
Labels: enhancement

#617 Feat/492 new menu
  src/app/components/Header/index.scss
  src/app/components/Header/index.tsx
  src/app/containers/StatsPage/components/AmmBalance.tsx
  src/app/containers/StatsPage/components/TVL.tsx
  src/app/containers/StatsPage/components/TradingVolume.tsx
  src/locales/en/translation.json
Labels: enhancement

#614 Feat/607 buy sov
  package.json
  src/app/components/Header/index.tsx
  src/app/components/PageHeader/index.tsx
  src/app/containers/Dialog/index.tsx
  src/app/containers/FastBtcDialog/components/transak.tsx
  src/app/containers/LendBorrowSovryn/assets/index.scss
  src/app/containers/WalletProvider/saga.ts
  src/app/index.tsx
  src/app/pages/BuySovPage/components/AmountButton/index.tsx
  src/app/pages/BuySovPage/components/ArrowStep/down.tsx
  src/app/pages/BuySovPage/components/ArrowStep/index.tsx
  src/app/pages/BuySovPage/components/Banner/index.tsx
  src/app/pages/BuySovPage/components/Button/buy.tsx
  src/app/pages/BuySovPage/components/Button/close.tsx
  src/app/pages/BuySovPage/components/Button/confirm.tsx
  src/app/pages/BuySovPage/components/Button/index.tsx
  src/app/pages/BuySovPage/components/BuyForm/Dialogs/SlippageDialog.tsx
  src/app/pages/BuySovPage/components/BuyForm/Dialogs/TxDialog.tsx
  src/app/pages/BuySovPage/components/BuyForm/Dialogs/dialog.module.css
  src/app/pages/BuySovPage/components/BuyForm/index.tsx
  src/app/pages/BuySovPage/components/BuyForm/useSlippage.ts
  src/app/pages/BuySovPage/components/Card/index.tsx
  src/app/pages/BuySovPage/components/EngageWallet/index.tsx
  src/app/pages/BuySovPage/components/Feature/index.tsx
  src/app/pages/BuySovPage/components/Features/StakeVote.tsx
  src/app/pages/BuySovPage/components/Features/index.tsx
  src/app/pages/BuySovPage/components/InfoBar/index.tsx
  src/app/pages/BuySovPage/components/Input/index.tsx
  src/app/pages/BuySovPage/components/Promotions/index.tsx
  src/app/pages/BuySovPage/components/Promotions/promotion.tsx
  src/app/pages/BuySovPage/components/Slider/index.tsx
  src/app/pages/BuySovPage/components/TopUpWallet/index.tsx
  src/app/pages/BuySovPage/components/Welcome/index.tsx
  src/app/pages/BuySovPage/index.tsx
  src/assets/images/arrow-down.svg
  src/assets/images/big-arrow-right.svg
  src/assets/images/confirm-tx.svg
  src/assets/images/dialog-close.svg
  src/assets/images/failed-tx.svg
  src/assets/images/pending-tx.svg
  src/assets/images/settings-white.svg
  src/assets/images/sov-welcome.svg
  src/assets/mt-feature.svg
  src/assets/placeholder.svg
  src/assets/sov/banner.svg
  src/assets/sov/promotion-1.svg
  src/assets/sov/promotion-2.svg
  src/assets/sov/stake-banner.svg
  src/locales/en/translation.json
  src/styles/sass/new-design.scss
  src/utils/helpers.ts
  yarn.lock
Labels: enhancement

#640 Release
  package.json
  public/maintenance.html
  src/app/components/TradingChart/index.tsx
  src/app/components/UserAssets/index.tsx
  src/app/containers/FastBtcDialog/components/TopUpHistory.tsx
  src/app/containers/LendBorrowSovryn/index.tsx
  src/app/containers/SwapHistory/index.tsx
  src/app/containers/TradingPage/index.tsx
  src/app/containers/WalletPage/index.tsx
  src/app/pages/BuySovPage/components/EngageWallet/index.tsx
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/pt_br/translation.json
  src/utils/classifiers.ts
  yarn.lock
Labels: release

#727 Fix/small bug fixes master
  src/app/containers/LiquidityMining/components/EventTable.tsx
  src/app/containers/SwapTradeForm/components/arbitrage.tsx
  src/app/pages/BuySovPage/components/EngageWallet/index.tsx
Labels: bug

#754 Issue/613 updated
  src/app/components/UserAssets/index.tsx
  src/app/containers/SwapHistory/index.tsx
  src/assets/images/icon-pending.svg
  src/assets/images/icon-rejected.svg
  src/assets/images/icon-success.svg
  src/styles/sass/new-design.scss
  src/utils/dictionaries/assets-dictionary.ts
Labels: enhancement

#779 New translations to PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#790 Feat/add fr translations
  src/app/components/LanguageToggle/index.tsx
  src/locales/fr/translation.json
  src/locales/i18n.ts
Labels: copy

#788 Fix typo in initial notification dialog
  src/locales/en/translation.json
Labels: copy

#809 rollbacks origin claiming #807
  src/app/containers/WalletPage/components/OriginClaimBanner.tsx
  src/app/containers/WalletPage/components/OriginClaimDialog.tsx
  src/app/containers/WalletPage/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#811 Disabled fiat ramp (fix #808), disabled fast btc if user is in wrong …
  src/app/containers/FastBtcDialog/components/BTCButton.tsx
  src/app/containers/FastBtcDialog/components/MainScreen.tsx
  src/locales/en/translation.json
Labels: enhancement

#787 Add bitcoin uri to FastBTC QR code
  src/app/components/Form/AddressQrCode/index.tsx
  src/app/containers/FastBtcDialog/components/MainScreen.tsx
  src/app/containers/LiquidityMining/components/EventTable.tsx
Labels: enhancement

#827 fix #735
  src/app/components/LoadableValue/index.tsx
  src/app/pages/BuySovPage/index.tsx
Labels: bug

#805 feat/601-add-wrong-network-flow
  src/app/components/BackButton/index.tsx
  src/app/components/NetworkDialog/index.module.css
  src/app/components/NetworkDialog/index.tsx
  src/app/components/NetworkRibbon.tsx
  src/app/components/NetworkRibbon/NetworkRibbon.tsx
  src/app/components/NetworkRibbon/_networkRibbon.scss
  src/app/components/NetworkRibbon/component/DetectionScreen.tsx
  src/app/components/NetworkRibbon/component/TutorialScreen.tsx
  src/app/components/NetworkRibbon/component/network.json
  src/app/containers/Dialog/index.tsx
  src/app/containers/FastBtcDialog/components/MainScreen.tsx
  src/app/containers/FastBtcDialog/components/TopUpHistory.tsx
  src/app/containers/FastBtcDialog/index.module.css
  src/app/containers/WalletConnector/index.tsx
  src/app/index.tsx
  src/assets/images/error_outline-24px.svg
  src/assets/wallet_icons/Metamask.svg
  src/assets/wallet_icons/liquality.svg
  src/assets/wallet_icons/nifty.svg
  src/assets/wallet_icons/portis.svg
  src/assets/wallet_tutorials/liquality/liquality_01.svg
  src/assets/wallet_tutorials/liquality/liquality_02.svg
  src/assets/wallet_tutorials/liquality/liquality_03.svg
  src/assets/wallet_tutorials/liquality/liquality_04.svg
  src/assets/wallet_tutorials/liquality/liquality_05.svg
  src/assets/wallet_tutorials/metamask/metamask_01.svg
  src/assets/wallet_tutorials/metamask/metamask_02.svg
  src/assets/wallet_tutorials/metamask/metamask_03.svg
  src/assets/wallet_tutorials/metamask/metamask_04.svg
  src/assets/wallet_tutorials/metamask/metamask_05.svg
  src/assets/wallet_tutorials/metamask/metamask_06.svg
  src/assets/wallet_tutorials/nifty/nifty_01.svg
  src/assets/wallet_tutorials/nifty/nifty_02.svg
  src/assets/wallet_tutorials/nifty/nifty_03.svg
Labels: enhancement

#877 feat/601_add_wrong_network_flow
  src/app/components/NetworkRibbon/NetworkRibbon.tsx
  src/app/components/NetworkRibbon/component/DetectionScreen.tsx
  src/app/components/NetworkRibbon/component/TutorialScreen.tsx
  src/locales/en/translation.json
Labels: copy, enhancement

#871 Add Tradingview chart attribution
  src/app/components/TradingChart/index.tsx
Labels: copy, enhancement

#732 Wallet connect integration test
  package.json
  yarn.lock
Labels: dependencies, enhancement

#907 feat/862_naming_display
  src/app/components/CurrencyAsset/index.module.css
  src/app/components/CurrencyAsset/index.tsx
  src/app/components/UserAssets/index.tsx
Labels: enhancement

#955 Escrow
  src/app/components/NetworkRibbon/component/network.json
  src/app/containers/LendBorrowSovryn/Loadable.tsx
  src/app/index.tsx
  src/app/pages/BuySovPage/Loadable.tsx
  src/app/pages/Escrow/Loadable.tsx
  src/app/pages/Escrow/components/Button/index.tsx
  src/app/pages/Escrow/components/DescriptionBlock/index.tsx
  src/app/pages/Escrow/components/EscrowForm/TxDialog.tsx
  src/app/pages/Escrow/components/EscrowForm/dialog.module.css
  src/app/pages/Escrow/components/EscrowForm/index.tsx
  src/app/pages/Escrow/components/InfoBar/index.tsx
  src/app/pages/Escrow/components/PoolTable/index.tsx
  src/app/pages/Escrow/hooks/useApproveAndDepositToken.ts
  src/app/pages/Escrow/hooks/useDepositToken.ts
  src/app/pages/Escrow/index.tsx
  src/locales/en/translation.json
  src/store/global/transactions-store/types.ts
  src/utils/blockchain/abi/EscrowRewardsAbi.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
Labels: enhancement

#958 Feat/930 liquidity rewards
  src/app/containers/LiquidityMining/components/RewardPool.tsx
  src/app/containers/LiquidityMining/components/RewardTable.tsx
  src/app/containers/LiquidityMining/components/SOVPoolData.tsx
  src/locales/en/translation.json
  src/locales/fr/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement

#964 move useMaintenance to WalletProvider.
  src/app/hooks/useMaintenance.ts
  src/app/index.tsx
Labels: enhancement
