Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2021-09, with the labels that each got.

#1676 Fix minReturn on swaps
  src/app/components/Form/AddressQrCode/index.tsx
  src/app/hooks/swap-network/useSwapNetwork_convertByPath.ts
Labels: bug

#1559 Margin trading with slippage
  src/app/containers/FastBtcDialog/saga.ts
  src/app/hooks/trading/useApproveAndTrade.ts
  src/app/hooks/trading/useDepositCollateral.ts
  src/app/hooks/trading/useMarginTrade.ts
  src/app/pages/MarginTradePage/components/OpenPositionsTable/OpenPositionRow.tsx
  src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
  src/utils/blockchain/abi/LoanTokenLogicStandard.json
  src/utils/blockchain/abi/LoanTokenLogicWrbtc.json
  src/utils/classifiers.ts
  src/utils/debug.ts
  src/utils/helpers.ts
  src/utils/sovryn/contract-reader.ts
Labels: do-not-merge!

#1682 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1638 Unhide cross-chain flow
  src/app/components/UserAssets/BridgeLink.tsx
Labels: enhancement

#1683 [Staking] - fix the issue with stake/unstake 100% of SOV
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/ExtendStakeForm.tsx
  src/app/containers/StakePage/components/IncreaseStakeForm.tsx
  src/app/containers/StakePage/components/StakeForm.tsx
  src/app/containers/StakePage/components/WithdrawForm.tsx
  src/app/containers/StakePage/index.tsx
  src/styles/tailwindcss/components.css
Labels: bug

#1687 Fix/cross chain gaslimit
  src/app/pages/BridgeDepositPage/components/AmountInput/index.tsx
  src/app/pages/BridgeDepositPage/saga.ts
  src/app/pages/BridgeWithdrawPage/components/AmountInput/index.tsx
  src/app/pages/BridgeWithdrawPage/saga.ts
  src/app/pages/BuySovPage/components/BuyForm/Dialogs/TxDialog.tsx
  src/store/global/transactions-store/types.ts
  src/utils/classifiers.ts
Labels: bug, enhancement

#1689 Update SOV amm pool Loot Drop promo rewards
  src/app/pages/LandingPage/components/Promotions/index.tsx
  src/app/pages/LiquidityMining/index.tsx
Labels: enhancement

#1686 Minor changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1706 [Styling] remove :focus outline
  src/styles/tailwindcss/base.css
Labels: bug

#1705 feat: add SOV as collateral for borrowing
  src/utils/dictionaries/lending-pool-dictionary.ts
Labels: enhancement

#1704 Add a warning if users want to withdraw to an external address
  src/app/components/Form/Input/index.tsx
  src/app/pages/BridgeWithdrawPage/components/AmountSelector/index.module.scss
  src/app/pages/BridgeWithdrawPage/components/AmountSelector/index.tsx
  src/app/pages/BridgeWithdrawPage/components/ReceiverSelector/index.module.scss
  src/app/pages/BridgeWithdrawPage/components/ReceiverSelector/index.tsx
  src/app/pages/BridgeWithdrawPage/components/TokenSelector/TokenItem.tsx
  src/app/pages/BridgeWithdrawPage/components/TokenSelector/index.tsx
  src/app/pages/BridgeWithdrawPage/index.tsx
  src/assets/images/warning_black_24dp.svg
  src/locales/en/translation.json
  src/styles/tailwindcss/components/inputs.css
Labels: enhancement

#1696 Define gas limit for origins claiming
  src/app/pages/OriginsClaimPage/components/ClaimForm/index.tsx
  src/utils/classifiers.ts
Labels: bug

#1698 Show daily scale ticks on the charts
  src/app/components/FinanceV2Components/ComparisonChart/Chart.tsx
Labels: enhancement

#1726 hotfix: wrong contract address used for busd bridge
  src/app/pages/BridgeDepositPage/dictionaries/assets/bsc-to-rsk.mainnet.ts
  src/app/pages/BridgeDepositPage/dictionaries/assets/bsc-to-rsk.testnet.ts
Labels: bug

#1725 fix qrcode - fiat btn style issue.
  src/app/containers/FastBtcDialog/components/FiatButton.tsx
  src/app/containers/WalletPage/index.tsx
  src/styles/tailwindcss/components/qrcode.css
Labels: bug

#1697 Feat/274 Pagination
  src/app/components/Pagination/index.module.scss
  src/app/components/Pagination/index.stories.tsx
  src/app/components/Pagination/index.tsx
  src/app/components/Pagination/index.utils.ts
Labels: enhancement

#1730 hotfix: release fixes
  src/app/hooks/staking/useStakeWithdraw.ts
  src/app/hooks/swap-network/useSwapNetwork_convertByPath.ts
  src/app/hooks/trading/useDepositCollateral.ts
  src/app/pages/BridgeDepositPage/hooks/useTokenBalance.ts
  src/app/pages/BuySovPage/components/BuyForm/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
  src/styles/sass/global.scss
  src/utils/classifiers.ts
Labels: bug, release

#1736 hotfix: bridge network going black on hardware wallets
  src/app/components/LinkToExplorer/index.tsx
  src/app/pages/BridgeDepositPage/utils/bridge-network.ts
Labels: bug, release

#1720 feat: add rdoc to portfolio and allow rdoc conversion to xusd
  src/app/components/AssetRenderer/index.tsx
  src/app/components/AssetSymbolRenderer/index.tsx
  src/app/components/UserAssets/ConversionDialog.tsx
  src/app/components/UserAssets/ConversionDialogContent.tsx
  src/app/components/UserAssets/TxDialog/index.tsx
  src/app/components/UserAssets/index.tsx
  src/app/hooks/portfolio/useConvertToXUSD.ts
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
  src/assets/images/tokens/rifd.svg
  src/types/asset.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/assets-dictionary.ts
Labels: enhancement

#1747 feat: send sov / esov over bridge
  src/app/components/UserAssets/index.tsx
  src/app/pages/BridgeDepositPage/components/ChainSelector/index.tsx
  src/app/pages/BridgeDepositPage/components/TokenSelector/index.tsx
  src/app/pages/BridgeDepositPage/dictionaries/assets/bsc-to-rsk.mainnet.ts
  src/app/pages/BridgeDepositPage/dictionaries/assets/bsc-to-rsk.testnet.ts
  src/app/pages/BridgeDepositPage/dictionaries/assets/rsk-to-bsc.mainnet.ts
  src/app/pages/BridgeDepositPage/dictionaries/assets/rsk-to-bsc.testnet.ts
  src/app/pages/BridgeDepositPage/types/bridge-model.ts
  src/app/pages/BridgeWithdrawPage/components/TokenSelector/index.tsx
Labels: enhancement

#1746 hide back button once it's disabled in cross chain withdraw.
  src/app/pages/BridgeWithdrawPage/components/SidebarSteps/index.tsx
Labels: bug

#1734 feat: switch between swaps external and rbtc proxy
  src/app/containers/SpotHistory/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
  src/app/pages/SpotTradingPage/types.ts
Labels: enhancement

#1740 SOV margin trading (long)
  src/app/components/TradingChart/index.tsx
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/utils/dictionaries/trading-pair-dictionary.ts
  src/utils/models/trading-pair.ts
Labels: enhancement

#1741 Origin FISH vesting withdraw
  src/app/components/CurrentPositionProfit/index.tsx
  src/app/components/UserAssets/FishDollarValue.tsx
  src/app/components/UserAssets/OriginsSaleRow.tsx
  src/app/components/UserAssets/VestedAssets.tsx
  src/app/components/UserAssets/Vesting/VestedItem.tsx
  src/app/components/UserAssets/Vesting/VestingUnlockScheduleDialog.tsx
  src/app/components/UserAssets/Vesting/VestingWithdrawDialog.tsx
  src/app/components/UserAssets/Vesting/VestingWithdrawForm.tsx
  src/app/components/UserAssets/Vesting/useListOfUserVestings.ts
  src/app/components/UserAssets/VestingDialog.tsx
  src/app/components/UserAssets/index.tsx
  src/app/components/UserAssets/useVestedStaking_balanceOf.ts
  src/app/containers/SpotHistory/AssetRow.tsx
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/components/WithdrawVesting.tsx
  src/app/containers/StakePage/index.tsx
  src/app/containers/SwapHistory/index.tsx
  src/app/containers/VestedHistory/index.tsx
  src/app/hooks/staking/useGetUnlockedVesting.ts
  src/app/hooks/useDollarValue.ts
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/app/pages/LandingPage/components/TradingVolume/index.tsx
  src/locales/en/translation.json
  src/utils/display-text/format.ts
Labels: enhancement

#1729 Minor changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1751 Release canditate
  src/app/components/MetaMaskDiscouragementNotifyModal/index.tsx
  src/locales/pt_br/translation.json
Labels: release

#1750 hotfix: sov/rbtc, sov/bpro pair naming and charts
  src/app/components/UserAssets/index.tsx
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/dictionaries/trading-pair-dictionary.ts
Labels: bug, hotfix

#1755 hotfix: use wrbtc wrapper proxy for bnbs swaps
  src/app/containers/SwapFormContainer/index.tsx
  src/app/pages/LandingPage/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
Labels: hotfix

#1757 Revert "hotfix: use wrbtc wrapper proxy for bnbs swaps"
  src/app/containers/SwapFormContainer/index.tsx
  src/app/pages/LandingPage/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
Labels: hotfix

#1762 feat: add Airdrop FISH vesting info to portfolio
  src/app/components/UserAssets/Vesting/useListOfUserVestings.ts
Labels: enhancement, release

#1761 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1773 chore: add get started banner
  src/app/pages/LandingPage/components/Banner/GetStartedBanner.tsx
  src/app/pages/LandingPage/index.tsx
  src/assets/images/banner/get_started.png
  src/locales/en/translation.json
Labels: enhancement

#1732 feat: added rif token and rbtc/rif amm converter pool
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/pages/SpotTradingPage/types.ts
  src/assets/images/tokens/rif.svg
  src/types/asset.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/dictionaries/liquidity-pool-dictionary.ts
Labels: enhancement, release

#1770 feat/remove-bridge-from-header
  src/app/components/Header/index.tsx
Labels: enhancement

#1777 chore: new get started banner image
  src/assets/images/banner/get_started.png
Labels: enhancement
