Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2021-06, with the labels that each got.

#1200 Add new strings and translate to PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1244 fixes collateral amount calculation for borrowing
  src/app/containers/LendBorrowSovryn/BorrowingContainer/index.tsx
  src/app/hooks/lending/useLending_getDepositAmountForBorrow.ts
  src/app/pages/OriginsLaunchpad/index.tsx
Labels: bug

#1243 moc/rbtc pool implementation
  src/app/components/UserAssets/index.tsx
  src/app/containers/LendBorrowSovryn/BorrowingContainer/index.tsx
  src/app/containers/StatsPage/components/AmmBalance.tsx
  src/app/hooks/lending/useLending_getDepositAmountForBorrow.ts
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/OriginsLaunchpad/index.tsx
  src/app/pages/SpotTradingPage/types.ts
  src/assets/images/tokens/moc.svg
  src/types/asset.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/dictionaries/liquidity-pool-dictionary.ts
Labels: release

#1267 New SOV/RBTC promo copy
  src/locales/en/translation.json
Labels: copy

#1256 [Staking] - fix usd balance #1255
  src/app/components/UserAssets/VestedAssets.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
Labels: enhancement

#1273 Fix approx rendering in current vests
  src/app/containers/StakePage/components/VestingContract.tsx
Labels: bug

#1275 autopilot email subscription
  src/app/pages/OriginsLaunchpad/components/EmailSubscribeSection/index.tsx
  src/app/pages/OriginsLaunchpad/components/EmailSubscribeSection/types.ts
  src/app/pages/OriginsLaunchpad/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1257 Minor change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1281 Update spot pair list
  src/app/pages/SpotTradingPage/types.ts
Labels: enhancement

#1284 Update Loot Drop promo copy
  src/app/pages/LiquidityMining/index.tsx
  src/locales/en/translation.json
Labels: copy

#1290 [Stats page] Add staked SOV to TVL
  src/app/containers/StatsPage/components/TVL.tsx
  src/app/containers/StatsPage/types.ts
  src/locales/en/translation.json
Labels: enhancement

#1291 [Yield Farm Page] Remove P/L and Total Earned
  src/app/pages/LiquidityMining/components/RowTable/index.tsx
Labels: bug

#1288 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1262 Feat/xusd rbtc
  src/app/components/UserAssets/index.tsx
  src/app/containers/StatsPage/components/AmmBalance.tsx
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/pages/SpotTradingPage/types.ts
  src/assets/images/tokens/xusd.svg
  src/types/asset.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/dictionaries/liquidity-pool-dictionary.ts
  yarn.lock
Labels: WIP, enhancement, release

#1282 Add rUSDT/ rBTC loot drop banner
  src/app/components/FinanceV2Components/LootDrop/styled.ts
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/index.tsx
Labels: WIP

#1310 Resolve issue withdrawing vested tokens
  src/app/containers/StakePage/components/WithdrawVesting.tsx
  src/app/containers/StakePage/index.tsx
  src/utils/blockchain/requests/vesting.ts
Labels: bug

#1308 [Lending] - fix MAX button on Lending UI is triggering a round-up err…
  src/app/containers/LendBorrowSovryn/LendingContainer/index.tsx
Labels: bug

#1297 bnb/rbtc pool
  src/app/components/AssetSymbolRenderer/index.tsx
  src/app/components/Form/Select/index.tsx
  src/app/components/Form/Select/renderers.tsx
  src/app/components/UserAssets/index.tsx
  src/app/containers/SwapHistory/index.tsx
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
  src/app/pages/SpotTradingPage/types.ts
  src/assets/images/tokens/bnb.svg
  src/assets/images/tokens/eth.svg
  src/types/asset.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/dictionaries/liquidity-pool-dictionary.ts
Labels: WIP

#1325 Improve language of README, fixing some grammar, stylistic improvemen…
  README.md
Labels: copy

#1334 Release
  README.md
  package.json
  src/app/containers/FastBtcDialog/components/FiatDialogScreen.tsx
  src/app/containers/FastBtcDialog/components/TransackScreen.tsx
  src/app/containers/FastBtcDialog/saga.ts
  src/app/containers/FastBtcDialog/slice.ts
  src/app/containers/LendBorrowSovryn/LendingContainer/index.tsx
  src/app/containers/SwapFormContainer/components/SwapAssetSelector/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/pages/SpotTradingPage/types.ts
  src/types/asset.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
  yarn.lock
Labels: release

#1332 Maintenance mode updates
  src/app/components/ActiveBorrowTable/index.tsx
  src/app/components/ActiveUserLoanContainer/components/ActiveLoanTableContainer/index.tsx
  src/app/components/Footer/index.tsx
  src/app/components/Form/ActionButton/index.tsx
  src/app/components/UserAssets/VestedAssets.tsx
  src/app/components/UserAssets/index.tsx
  src/app/containers/BorrowHistory/index.tsx
  src/app/containers/LendBorrowSovryn/BorrowingContainer/index.tsx
  src/app/containers/LendBorrowSovryn/components/TabContainer/index.tsx
  src/app/containers/LiquidityAddContainer/PoolV1.tsx
  src/app/containers/LiquidityAddContainer/index.tsx
  src/app/containers/LiquidityRemoveContainer/RemovePoolV1.tsx
  src/app/containers/LiquidityRemoveContainer/index.tsx
  src/app/containers/MaintenancePage/index.tsx
  src/app/containers/RepayPositionHandler/RepayPositionForm.tsx
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/hooks/useMaintenance.ts
  src/app/index.tsx
  src/app/pages/BuySovPage/components/Button/buy.tsx
  src/app/pages/BuySovPage/components/BuyForm/index.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/AddLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/RemoveLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/MarginTradePage/components/AddToMarginDialog/index.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/OpenPositionRow.tsx
  src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForm/index.tsx
  src/app/pages/SpotTradingPage/components/PriceHistory/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
  src/locales/en/translation.json
  src/store/global/maintenance-store/saga.ts
  src/store/global/maintenance-store/types.ts
  src/utils/classifiers.ts
  src/utils/display-text/format.ts
Labels: enhancement

#1328 Metamask modal - add RSK Mainnet
  src/app/components/NetworkRibbon/component/DetectionScreen.tsx
  src/locales/en/translation.json
  src/utils/metamaskHelpers.ts
Labels: enhancement

#1353 [Staking] Add maintenance to modals
  src/app/containers/MaintenancePage/index.tsx
  src/app/containers/StakePage/components/DelegateForm.tsx
  src/app/containers/StakePage/components/ExtendStakeForm.tsx
  src/app/containers/StakePage/components/IncreaseStakeForm.tsx
  src/app/containers/StakePage/components/StakeForm.tsx
  src/app/containers/StakePage/components/WithdrawConfimationForm.tsx
  src/app/containers/StakePage/components/WithdrawForm.tsx
  src/app/containers/StakePage/components/WithdrawVesting.tsx
  src/app/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1349 Feat/improved arb copy
  src/app/components/Arbitrage/Arbitrage.tsx
  src/locales/en/translation.json
Labels: copy

#1356 [Header] Add Bridge menu option, spacing tweaks for smaller screens
  src/app/components/Header/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1348 [Yield Farm] Add history charts for pool AER
  src/app/components/FinanceV2Components/CardRow/index.tsx
  src/app/components/FinanceV2Components/ComparisonChart/index.tsx
  src/app/components/FinanceV2Components/RowTable/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/PoolChart.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/types.ts
  src/app/pages/LiquidityMining/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1358 Fix/1355 swap asset logic
  src/app/components/AssetSymbolRenderer/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/containers/SwapHistory/index.tsx
Labels: bug

#1361 Fix broken translation file
  src/locales/pt_br/translation.json
Labels: bug

#1365 [Stats] Fix TVL display issue on slow connections
  src/app/containers/StatsPage/components/TVL.tsx
Labels: bug

#1367 [Trading Chart] Store user drawings/indicators
  src/app/components/TradingChart/index.tsx
  src/app/components/TradingChart/storage.ts
  src/app/components/TradingChart/streaming.ts
  src/utils/classifiers.ts
Labels: enhancement

#1371 Feat/xusd trading
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/app/pages/MarginTradePage/slice.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/lending-pool-dictionary.ts
  src/utils/dictionaries/trading-pair-dictionary.ts
  src/utils/models/trading-pair.ts
Labels: WIP

#1373 Feat/1329 convert rusdt to xusd
  src/app/components/ActiveUserLoanContainer/components/DisplayDate/index.tsx
  src/app/components/Form/AmountInput/index.tsx
  src/app/components/Form/FormGroup/index.tsx
  src/app/components/UserAssets/ConversionDialog.tsx
  src/app/components/UserAssets/TxDialog/Status.tsx
  src/app/components/UserAssets/TxDialog/Title.tsx
  src/app/components/UserAssets/TxDialog/WalletLogo.tsx
  src/app/components/UserAssets/TxDialog/dialog.module.css
  src/app/components/UserAssets/TxDialog/index.tsx
  src/app/components/UserAssets/TxDialog/styled.ts
  src/app/components/UserAssets/index.tsx
  src/app/components/UserAssets/styled.ts
  src/app/hooks/portfolio/useConvertToXUSD.ts
  src/app/pages/MarginTradePage/components/TxFeeCalculator/index.tsx
  src/assets/images/babelfish.svg
  src/locales/en/translation.json
  src/store/global/transactions-store/types.ts
  src/utils/blockchain/abi/BabelfishAggregator.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
  tailwind.config.js
Labels: enhancement

#1377 [Yield Farm] Add missing wei to BTC conversion
  src/app/pages/LiquidityMining/components/MiningPool/PoolChart.tsx
Labels: bug

#1382 Feat/1380 aer apy chart
  src/app/pages/LiquidityMining/components/MiningPool/PoolChart.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement

#1383 bug/1339-staking-end-date
  src/app/containers/StakePage/components/VestingContract.tsx
Labels: bug

#1340 lending using lm
  src/app/containers/LendBorrowSovryn/LendingContainer/index.tsx
  src/app/containers/LendBorrowSovryn/components/ButtonGroup/index.tsx
  src/app/containers/LendBorrowSovryn/index.tsx
  src/app/hooks/lending/useLending_balanceOf.ts
  src/app/hooks/lending/useLending_burn.ts
  src/app/hooks/lending/useLending_mint.ts
  src/utils/blockchain/abi/LiquidityMining.json
  src/utils/blockchain/abi/LoanTokenLogicStandard.json
  src/utils/blockchain/abi/LoanTokenLogicWrbtc.json
Labels: enhancement

#1379 Add new strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1393 updated amm contracts
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/utils/blockchain/contracts.testnet.ts
Labels: enhancement

#1394 [Trading Chart] Increase indicator limit
  src/app/components/TradingChart/index.tsx
Labels: enhancement

#1399 bug/1391-margin-trade-fee
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
  src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
  src/app/pages/MarginTradePage/components/TxFeeCalculator/index.tsx
Labels: bug
