Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2021-11, with the labels that each got.

#1845 fix: add copy to explain circulating supply calculation change
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/locales/en/translation.json
Labels: copy, WIP

#1850 Fix/zero reward claim
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/types.ts
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/hooks/useClaimRewardSov.tsx
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
  src/app/pages/RewardPage/components/RewardTab/hooks/useGetTotalLiquidityRewards.ts
  src/app/pages/RewardPage/components/RewardTab/index.tsx
Labels: bug

#1834 Feat/508 swap data attributes
  src/app/components/AvailableBalance/index.tsx
  src/app/components/Form/AmountInput/index.tsx
  src/app/components/Form/Input/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/pages/BuySovPage/components/BuyForm/Dialogs/SlippageDialog.tsx
  src/app/pages/BuySovPage/components/BuyForm/Dialogs/dialog.module.scss
  src/app/pages/BuySovPage/components/BuyForm/index.tsx
Labels: enhancement

#1854 feat: enable browser based wallets for mobile devices
  src/app/containers/WalletConnector/index.tsx
  src/global.d.ts
  src/locales/en/translation.json
  src/utils/helpers.ts
Labels: enhancement, do-not-merge!

#1781 Feat/tenderly estimator
  .env.example
  CHANGELOG.md
  src/app/components/LoadableValue/index.tsx
  src/app/hooks/simulator/useFilterSimulatorResponseLogs.ts
  src/app/hooks/simulator/useSimulator.ts
  src/app/hooks/trading/usePositionLiquidationPrice.ts
  src/app/pages/MarginTradePage/components/AddToMarginDialog/index.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/DialogContent.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/OpenPositionRow.tsx
  src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
  src/app/pages/MarginTradePage/components/TxFeeCalculator/index.tsx
  src/locales/en/translation.json
  src/store/global/transactions-store/types.ts
  src/types/active-loan.ts
  src/utils/blockchain/leverage-from-start-margin.ts
  src/utils/classifiers.ts
  src/utils/simulator/helpers.ts
  src/utils/simulator/simulateTx.ts
  src/utils/simulator/types.ts
Labels: enhancement

#1858 Change string PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1859 Add strings PT-BR of Pull 1781
  src/locales/pt_br/translation.json
Labels: copy

#1861 fix: swap tx's showing WRBTC, tx's not appearing in spot history
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
Labels: bug

#1870 feat: add deposit button to header, xusd asset icons to portfolio, re…
  src/app/components/Header/index.tsx
  src/app/components/UserAssets/BridgeLink.tsx
  src/app/components/UserAssets/index.module.scss
  src/app/components/UserAssets/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1866 Minor changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1878 Feat/close mynt sale
  src/app/index.tsx
  src/app/pages/OriginsLaunchpad/index.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCard/index.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCardSection/index.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCardSection/module.scss
Labels: enhancement

#1880 hotfix: use wrbtc proxy instead of swaps external module for swaps
  src/app/containers/SwapFormContainer/index.tsx
  src/app/hooks/swap-network/useSwapNetwork_approveAndConvertByPath.ts
  src/app/hooks/swap-network/useSwapNetwork_convertByPath.ts
  src/app/pages/BuySovPage/components/BuyForm/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
Labels: bug

#1883 Release notes configurations
  .github/release.yml
Labels: internal, exclude-from-release

#1882 Master to development
  src/app/components/Header/index.tsx
  src/app/components/UserAssets/BridgeLink.tsx
  src/app/components/UserAssets/index.module.scss
  src/app/components/UserAssets/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/hooks/swap-network/useSwapNetwork_approveAndConvertByPath.ts
  src/app/hooks/swap-network/useSwapNetwork_convertByPath.ts
  src/app/index.tsx
  src/app/pages/BuySovPage/components/BuyForm/index.tsx
  src/app/pages/OriginsLaunchpad/index.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCard/index.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCardSection/index.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCardSection/module.scss
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
  src/locales/en/translation.json
Labels: exclude-from-release

#1884 hotfix: transactions failing on buy sov page
  src/app/hooks/swap-network/useSwapNetwork_convertByPath.ts
  src/app/pages/BuySovPage/components/BuyForm/index.tsx
Labels: bug

#1886 make sure contract calls uses at least 40k gas
  .github/release.yml
  src/utils/classifiers.ts
  src/utils/sovryn/contract-writer.ts
Labels: bug

#1890 Add strings and translate to PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1896 feat: bump staking withdraw gas limit for HW users
  src/app/pages/LandingPage/components/Promotions/index.tsx
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/utils/classifiers.ts
Labels: bug

#1897 New strings and translate to PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1900 Release 2021 11 23
  src/app/pages/LandingPage/components/TotalValueLocked/index.tsx
  src/locales/en/translation.json
  src/utils/classifiers.ts
Labels: bug, enhancement, release

#1836 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy
