Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2021-12, with the labels that each got.

#1918 fix: deprecate /ws nodes
  src/utils/classifiers.ts
Labels: internal

#1911 Add new strings and translate to PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1906 changed testnet amm converter addresses
  src/utils/blockchain/contracts.testnet.ts
Labels: exclude-from-release

#1874 Fix margin trading P/L issues
  src/app/components/Dialogs/TxDialog.tsx
  src/app/components/Form/Input/index.tsx
  src/app/hooks/simulator/useFilterSimulatorResponseLogs.ts
  src/app/hooks/useCacheCall.ts
  src/app/pages/MarginTradePage/components/AddToMarginDialog/index.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/DialogContent.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/OpenPositionRow.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/ProfitContainer.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/helpers.ts
  src/app/pages/MarginTradePage/components/OpenPositionsTable/index.tsx
  src/app/pages/MarginTradePage/components/TradingHistory/index.tsx
  src/locales/en/translation.json
  src/utils/blockchain/leverage-from-start-margin.ts
  src/utils/classifiers.ts
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/display-text/format.ts
  src/utils/helpers.ts
  src/utils/models/asset-details.ts
  src/utils/sovryn/contract-reader.ts
Labels: bug

#1927 Release 2021 12 07
  src/app/pages/LandingPage/components/Promotions/components/PromotionCard/styled.ts
  src/app/pages/LiquidityMining/hooks/useLiquidityMining_getPoolId.ts
  src/utils/classifiers.ts
Labels: bug, exclude-from-release

#1909 Minor change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1931 Release 2021-12-07
  src/app/components/Dialogs/TxDialog.tsx
  src/app/components/Form/Input/index.tsx
  src/app/hooks/simulator/useFilterSimulatorResponseLogs.ts
  src/app/hooks/useCacheCall.ts
  src/app/pages/LandingPage/components/Promotions/components/PromotionCard/styled.ts
  src/app/pages/LandingPage/components/Promotions/index.tsx
  src/app/pages/LandingPage/components/TotalValueLocked/index.tsx
  src/app/pages/LiquidityMining/hooks/useLiquidityMining_getPoolId.ts
  src/app/pages/MarginTradePage/components/AddToMarginDialog/index.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/DialogContent.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/OpenPositionRow.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/ProfitContainer.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/helpers.ts
  src/app/pages/MarginTradePage/components/OpenPositionsTable/index.tsx
  src/app/pages/MarginTradePage/components/TradingHistory/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/leverage-from-start-margin.ts
  src/utils/classifiers.ts
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/display-text/format.ts
  src/utils/helpers.ts
  src/utils/models/asset-details.ts
  src/utils/sovryn/contract-reader.ts
Labels: release, exclude-from-release

#1921 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1940 feat(labs): add link to zero in header(testnet only)
  src/app/components/Header/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#1901 Minor changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1943 feat: new AMM pool addresses, feeSharingProxy ABI
  src/utils/blockchain/abi/FeeSharingProxy.json
  src/utils/blockchain/contracts.ts
Labels: release

#1945 Master to development
  src/utils/blockchain/abi/FeeSharingProxy.json
  src/utils/blockchain/contracts.ts
Labels: exclude-from-release

#1949 fix: bump gas limit for unlend, ensure lend/unlend respects gas limits
  src/app/hooks/lending/useLending_burn.ts
  src/app/hooks/lending/useLending_mint.ts
  src/utils/classifiers.ts
Labels: bug

#1953 Master
  src/app/hooks/lending/useLending_burn.ts
  src/app/hooks/lending/useLending_mint.ts
  src/utils/classifiers.ts
Labels: exclude-from-release

#1942 Changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1923 Swap WS nodes with RPC nodes
  package.json
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/WalletProvider/saga.ts
  src/app/containers/WalletProvider/slice.ts
  src/app/containers/WalletProvider/types.ts
  src/app/hooks/trading/useCachedAssetPrice.ts
  src/utils/classifiers.ts
  src/utils/sovryn/sovryn-network.ts
  yarn.lock
Labels: enhancement

#1961 mynt amm pool
  src/app/components/UserAssets/index.tsx
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/hooks/useDollarValueMynt.ts
  src/app/hooks/useEstimateMyntToSov.ts
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/SpotTradingPage/types.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/liquidity-pool-dictionary.ts
Labels: enhancement

#1962 mynt amm pool (#1961)
  src/app/components/UserAssets/index.tsx
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/hooks/useDollarValueMynt.ts
  src/app/hooks/useEstimateMyntToSov.ts
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/SpotTradingPage/types.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/liquidity-pool-dictionary.ts
Labels: exclude-from-release

#1963 feat(mynt): add MYNT token under labs
  src/app/components/Header/index.tsx
  src/locales/en/translation.json
Labels: enhancement, exclude-from-release

#1966 feat(amm): amm pool upgrade
  .env.mainnet.local
  src/app/components/FinanceV2Components/LootDrop/styled.ts
  src/app/pages/LandingPage/components/Promotions/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/utils/blockchain/contracts.ts
Labels: enhancement

#1959 allow ethereum HD derivation paths
  package.json
  yarn.lock
Labels: enhancement, dependencies

#1973 hotfix(rewards): unable to claim rewards using HW
  src/app/hooks/useSendContractTx.ts
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/hooks/useClaimRewardSov.tsx
Labels: bug

#1974 hotfix(rewards): unable to claim rewards using HW (#1973)
  src/app/hooks/useSendContractTx.ts
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/hooks/useClaimRewardSov.tsx
Labels: exclude-from-release
