Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2022-04, with the labels that each got.

#2118 Get spot limitPrice from events
  src/app/components/RecentTrades/RecentTradeRow.tsx
  src/app/hooks/limitOrder/useLimitOrder.ts
  src/app/hooks/useMaintenance.ts
  src/app/pages/MarginTradePage/components/LimitOrder/CloseLimitPositionDialog/index.tsx
  src/app/pages/MarginTradePage/components/LimitOrder/LimitOrderHistory/index.tsx
  src/app/pages/MarginTradePage/components/LimitOrder/LimitOrderRow/index.tsx
  src/app/pages/MarginTradePage/components/LimitOrder/LimitTradeDialog/index.tsx
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/ClosePositionDialog/index.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/LimitOrderHistory/index.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/LimitOrderRow.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/OpenPositionsTable/index.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/LimitForm.tsx
  src/utils/blockchain/abi/OrderBook.json
  src/utils/blockchain/abi/Settlement.json
  src/utils/blockchain/app-contracts.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
  src/utils/sovryn/sovryn-network.ts
  src/utils/types/contracts.ts
Labels: enhancement

#2120 [Header] - Bitocracy link in testnet Dapp menu pointing to tesnet site
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/containers/StakePage/index.tsx
  src/utils/classifiers.ts
Labels: enhancement

#2126 show BTC instead of BTCS
  src/app/pages/PerpetualPage/components/ClosedPositionsTable/ClosedPositionRow.tsx
  src/app/pages/PerpetualPage/components/OpenPositionsTable/components/OpenPositionRow.tsx
Labels: enhancement

#2071 feat(bridge): btcs -> rbtc transfers
  package.json
  src/app/pages/FastBtcPage/components/Withdraw/AddressForm.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
  src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  yarn.lock
Labels: enhancement

#2105 [Picture] - add picture component
  src/app/components/Picture/index.stories.tsx
  src/app/components/Picture/index.tsx
Labels: refactoring

#2107 Feat/2255734392 overlay component
  public/index.html
  src/app/components/Overlay/index.stories.tsx
  src/app/components/Overlay/index.tsx
  src/app/components/Portal/index.tsx
  src/types/tailwind.ts
Labels: enhancement

#2127 [Switch] - switch cleanup
  src/app/components/Switch/index.module.scss
  src/app/components/Switch/index.tsx
Labels: enhancement

#2133 Fix edit margin action
  package.json
  src/app/pages/PerpetualPage/components/EditMarginDialog/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
  yarn.lock
Labels: bug

#2116 Feat: Storybook Design Guide
  .storybook/preview.js
  .storybook/webpack.config.js
  package.json
  src/app/components/Storybook/animations.stories.tsx
  src/app/components/Storybook/borders.stories.tsx
  src/app/components/Storybook/colors.stories.tsx
  src/app/components/Storybook/components/StorybookAnimatedBox.tsx
  src/app/components/Storybook/components/StorybookSwatch.tsx
  src/app/components/Storybook/components/StorybookTailwindUsage.tsx
  src/app/components/Storybook/components/StorybookTextSample.tsx
  src/app/components/Storybook/sizes.stories.tsx
  src/app/components/Storybook/text.stories.tsx
  src/app/components/Storybook/transitions.stories.tsx
  src/app/components/Table/index.tsx
  tailwind.config.js
Labels: enhancement

#2072 fix(staking): page inconsistencies
  src/app/components/UserAssets/Vesting/useListOfUserVestings.ts
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/CurrentVests.tsx
  src/app/containers/StakePage/components/FeeBlock.tsx
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/index.tsx
  src/app/hooks/staking/useStaking_getAccumulatedFees.ts
  src/styles/sass/new-design.scss
  src/utils/blockchain/abi/FeeSharingProxy.json
  src/utils/models/margin-pair.ts
Labels: bug

#2134 Minor changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2144 feat: header link to mynt bonding curve
  src/app/components/Header/index.tsx
Labels: release

#2143 Feat/2415405512 dropdown atomic component
  src/app/components/Dropdown/index.module.scss
  src/app/components/Dropdown/index.stories.tsx
  src/app/components/Dropdown/index.tsx
  src/app/components/Dropdown/types.ts
  src/app/components/Dropdown/utils.ts
  src/app/components/PairNavbar/PairSelect.tsx
  src/app/components/Storybook/animations.stories.tsx
  src/app/containers/SwapFormContainer/components/SwapSelector/index.tsx
  src/app/hooks/useOnClickOutside.ts
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/app/pages/PerpetualPage/components/PairSelector/PairSelectorButton.tsx
Labels: enhancement

#2152 [RadioButton] - add RadioButton component
  src/app/components/RadioButton/index.module.scss
  src/app/components/RadioButton/index.stories.tsx
  src/app/components/RadioButton/index.tsx
  src/app/components/RadioButton/types.ts
Labels: enhancement

#2131 GraphQL codegen
  .env.local
  .env.mainnet.local
  .env.production
  .env.testnet
  codegen.fetch.yml
  codegen.yml
  package.json
  src/index.tsx
  src/utils/classifiers.ts
  src/utils/graphql/README.md
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/users.graphql
  src/utils/graphql/rsk/schema.graphql
  yarn.lock
Labels: enhancement
