Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2022-03, with the labels that each got.

#2078 Update FastBTC UI copy and fix typos
  src/locales/en/translation.json
Labels: copy

#2054 Minor change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2073 Checkbox atomic component
  src/app/components/Checkbox/index.module.scss
  src/app/components/Checkbox/index.stories.tsx
  src/app/components/Checkbox/index.tsx
Labels: refactoring

#2082 Fix Perpetuals data fetching issues
  src/app/components/UserAssets/Vesting/useGetVesting.ts
  src/app/hooks/useBridgeNetworkMultiCall.ts
  src/app/pages/BridgeDepositPage/utils/bridge-network.ts
  src/app/pages/FastBtcPage/hooks/useWithdrawBridgeConfig.ts
  src/app/pages/PerpetualPage/components/TradingChart/index.tsx
  src/app/pages/PerpetualPage/contexts/PerpetualQueriesContext.tsx
  src/app/pages/PerpetualPage/contexts/RecentTradesContext.tsx
  src/app/pages/PerpetualPage/hooks/graphql/useGetRecentTrades.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_queryAmmState.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_queryLiqPoolId.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_queryLiqPoolStateFromPerpetualId.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_queryPerpParameters.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_queryTraderState.ts
  src/app/pages/PerpetualPage/utils/bscWebsocket.ts
  src/app/pages/PerpetualPage/utils/contractUtils.tsx
  src/app/pages/RewardPage/components/RewardTab/hooks/useGetAvailableLendingRewards.ts
  src/app/pages/RewardPage/components/RewardTab/hooks/useGetAvailableLiquidityRewards.ts
  src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
Labels: bug

#2084 Design changes
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/AmmDepthChart/AmmDepthChartRow.tsx
  src/app/pages/PerpetualPage/components/AmmDepthChart/index.tsx
  src/app/pages/PerpetualPage/components/ContractDetails/index.tsx
  src/app/pages/PerpetualPage/components/DataCard/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
  src/app/pages/PerpetualPage/components/OpenPositionsTable/components/OpenPositionRow.tsx
  src/app/pages/PerpetualPage/components/OpenPositionsTable/index.tsx
  src/app/pages/PerpetualPage/components/PairSelector/PairSelectorButton.tsx
  src/app/pages/PerpetualPage/components/RecentTradesTable/components/RecentTablesRow/index.tsx
  src/app/pages/PerpetualPage/components/RecentTradesTable/index.tsx
  src/app/pages/PerpetualPage/components/RecentTradesTable/utils.tsx
  src/app/pages/PerpetualPage/components/TradingChart/index.tsx
  src/app/pages/PerpetualPage/hooks/usePerpetual_ContractDetails.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_OpenPositions.ts
  src/app/pages/PerpetualPage/index.module.scss
  src/assets/images/trend-arrow-down.svg
  src/assets/images/trend-arrow-up.svg
  src/locales/en/translation.json
  tailwind.config.js
Labels: enhancement

#2076 Form group atomic component
  src/app/components/FormGroup/index.stories.tsx
  src/app/components/FormGroup/index.tsx
  src/assets/images/info_icon.svg
Labels: refactoring

#2085 Minor change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2089 limit order fixes
  src/app/components/FormGroup/index.stories.tsx
  src/app/components/FormGroup/index.tsx
  src/app/containers/WalletProvider/slice.ts
  src/app/hooks/trading/useCachedAssetPrice.ts
  src/app/hooks/trading/useDenominateDollarToAssetAmount.ts
  src/app/pages/MarginTradePage/components/LimitOrder/LimitOrderHistory/index.tsx
  src/app/pages/MarginTradePage/components/LimitOrder/LimitOrderRow/index.tsx
  src/app/pages/MarginTradePage/components/LimitOrder/OpenPositionsTable/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/OpenPositionRow.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/PendingPositionRow.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/index.tsx
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/LimitOrderRow.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/OpenPositionsTable/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/LimitForm.tsx
  src/assets/images/info_icon.svg
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement

#2087 hotfix: upgrade staking rewards liquid withdrawals
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/types.ts
  src/app/pages/RewardPage/components/ClaimForms/LiquidClaimForm/index.tsx
  src/app/pages/RewardPage/components/LiquidTab/index.tsx
  src/app/pages/RewardPage/hooks/useGetLiquidSovClaimAmount.ts
  src/app/pages/RewardPage/index.module.scss
  src/app/pages/RewardPage/index.tsx
  src/utils/blockchain/abi/StakingRewards.json
  src/utils/blockchain/contracts.testnet.ts
Labels: bug, release

#2090 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2079 Spinner enforcement
  src/app/components/Form/ActionButton/index.tsx
  src/app/components/Form/Button/index.tsx
  src/app/components/Form/TradeButton/index.tsx
  src/app/components/SalesButton/index.tsx
  src/app/components/Spinner/index.tsx
  src/app/components/Spinner/types.ts
  src/app/components/TradeButton/index.tsx
  src/app/components/UserAssets/Vesting/VestedItem.tsx
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/index.tsx
  src/app/containers/WalletConnector/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/EngageWalletStep/index.tsx
  src/styles/tailwindcss/components.css
  src/styles/tailwindcss/components/btn-action.css
  src/styles/tailwindcss/components/dialog-btn.css
  src/styles/tailwindcss/components/engage-btn.css
  src/styles/tailwindcss/components/trade-btn.css
Labels: refactoring

#2074 fix(staking): add missing tx confirmation modals
  src/app/containers/StakePage/components/FeeBlock.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/components/WithdrawVesting.tsx
  src/app/containers/StakePage/index.tsx
  src/utils/blockchain/requests/staking.ts
  src/utils/blockchain/requests/vesting.ts
Labels: bug

#2094 Minor changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2097 add switch atomic component
  src/app/components/Switch/index.module.scss
  src/app/components/Switch/index.stories.tsx
  src/app/components/Switch/index.tsx
Labels: refactoring

#2086 Perpetual layout menu
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/ContractDetails/index.tsx
  src/app/pages/PerpetualPage/components/DataCard/index.tsx
  src/app/pages/PerpetualPage/components/LayoutMenu/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
  src/app/pages/PerpetualPage/slice.ts
  src/app/pages/PerpetualPage/types.ts
  src/assets/images/xmark.svg
  src/locales/en/translation.json
Labels: enhancement

#2099 feat: maintenance mode for FastBTC flow
  src/app/components/UserAssets/index.tsx
  src/app/pages/FastBtcPage/components/Deposit/MainScreen.tsx
  src/app/pages/FastBtcPage/components/Withdraw/AddressForm.tsx
  src/app/pages/FastBtcPage/components/Withdraw/AmountForm.tsx
  src/app/pages/FastBtcPage/components/Withdraw/MainScreen.tsx
  src/app/pages/FastBtcPage/components/Withdraw/ReviewScreen.tsx
  src/locales/en/translation.json
Labels: enhancement

#2092 FastBTC Signature Validation
  package.json
  src/app/__tests__/index.test.tsx
  src/app/pages/FastBtcPage/components/Deposit/AddressForm.tsx
  src/app/pages/FastBtcPage/components/Deposit/SidebarStepsDeposit.tsx
  src/app/pages/FastBtcPage/components/Deposit/SignatureValidation/index.module.scss
  src/app/pages/FastBtcPage/components/Deposit/SignatureValidation/index.tsx
  src/app/pages/FastBtcPage/containers/DepositContainer.tsx
  src/app/pages/FastBtcPage/contexts/deposit-context.ts
  src/app/pages/FastBtcPage/hooks/useDepositSocket.ts
  src/locales/en/translation.json
  src/store/__tests__/configureStore.test.ts
  src/store/__tests__/reducer.test.ts
  src/utils/blockchain/abi/fastBtcMultisig.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/signature/addressMappingSIgnature.ts
  src/utils/signature/signatureValidation.test.ts
  src/utils/signature/signatureValidation.ts
  yarn.lock
Labels: enhancement

#2095 [Perpetuals] disable perpetuals on mainnet
  src/app/components/Header/index.tsx
  src/app/index.tsx
Labels: refactoring

#2102 switch charting_library package
  .npmrc.pages
  README.md
  bin/gh-pack
  package.json
  scripts/copy-chart-libs.js
  src/app/components/TradingChart/index.tsx
  yarn.lock
Labels: bug

#2104 [Storybook] fix root styling issue, add dapp fonts
  .storybook/preview-head.html
  .storybook/preview.js
  src/styles/sass/global.scss
Labels: internal

#2098 universal header component (part 1)
  package.json
  src/app/components/NotFoundPage/index.tsx
  src/app/components/PageSkeleton/index.tsx
  src/app/containers/EmailPage/index.tsx
  src/app/containers/PageContainer/PageContainer.tsx
  src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/index.module.scss
  src/app/containers/PageContainer/context/PageContext.ts
  src/app/containers/PageContainer/context/actions.ts
  src/app/containers/PageContainer/context/reducer.ts
  src/app/containers/PageContainer/hooks/index.ts
  src/app/containers/PageContainer/hooks/usePage.ts
  src/app/containers/PageContainer/index.tsx
  src/app/containers/PageContainer/types.ts
  src/app/containers/StakePage/index.tsx
  src/app/containers/SwapPage/index.tsx
  src/app/containers/WalletPage/index.tsx
  src/app/index.tsx
  src/app/pages/BorrowPage/index.tsx
  src/app/pages/BridgeDepositPage/components/UserWallet/index.tsx
  src/app/pages/BridgeDepositPage/index.tsx
  src/app/pages/BridgeWithdrawPage/index.tsx
  src/app/pages/BuySovPage/index.tsx
  src/app/pages/FastBtcPage/components/FastBtcHeader.tsx
  src/app/pages/FastBtcPage/index.tsx
  src/app/pages/LandingPage/index.tsx
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/MarginTradePage/index.tsx
  src/app/pages/OriginsClaimPage/index.tsx
  src/app/pages/OriginsLaunchpad/index.tsx
  src/app/pages/RewardPage/index.tsx
  src/app/pages/SpotTradingPage/index.tsx
  yarn.lock
Labels: refactoring

#2106 hotfix: respect staking contract pause/freeze state
  .npmrc.pages
  README.md
  bin/gh-pack
  package.json
  scripts/copy-chart-libs.js
  src/app/components/AlertBadge/AlertBadge.tsx
  src/app/components/TradingChart/index.tsx
  src/app/components/UserAssets/VestedAssets.tsx
  src/app/components/UserAssets/Vesting/VestedItem.tsx
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/CurrentVests.tsx
  src/app/containers/StakePage/components/FeeBlock.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/index.tsx
  src/app/hooks/useContractPauseState.ts
  src/app/hooks/useIsMounted.ts
  src/locales/en/translation.json
  src/utils/blockchain/abi/Staking.json
  yarn.lock
Labels: hotfix

#2112 feat: disable Reward SOV claiming when staking contract paused
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
Labels: hotfix

#1681 Feat/252 button
  src/app/components/Button/index.module.scss
  src/app/components/Button/index.stories.tsx
  src/app/components/Button/index.tsx
  src/app/components/UserAssets/Vesting/VestingWithdrawForm.tsx
  src/app/components/UserAssets/Vesting/types.ts
  src/app/components/UserAssets/index.tsx
  src/app/containers/WalletPage/components/OriginClaimDialog.tsx
  src/app/pages/BridgeDepositPage/components/ReviewStep/index.tsx
  src/app/pages/BridgeWithdrawPage/components/ReviewStep/index.tsx
  src/app/pages/FastBtcPage/components/FastBtcButton.tsx
  src/app/pages/LandingPage/components/Banner/GetStartedBanner.tsx
  src/app/pages/LandingPage/components/Banner/index.tsx
  src/app/pages/OriginsClaimPage/components/ClaimForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
  src/utils/blockchain/abi/VestingRegistry.json
Labels: enhancement

#1691 Feat/276 Table
  src/app/components/Dialogs/dialog.module.scss
  src/app/components/Table/components/TableRow/index.module.scss
  src/app/components/Table/components/TableRow/index.tsx
  src/app/components/Table/index.module.scss
  src/app/components/Table/index.stories.tsx
  src/app/components/Table/index.tsx
  src/app/components/Table/types.ts
  src/assets/images/ellipsis-h.svg
  src/locales/en/translation.json
  src/styles/__tests__/media.test.ts
  src/styles/media.ts
  src/types/index.ts
  src/types/tailwind.ts
Labels: enhancement

#1699 Feat/259 heading
  src/app/components/Heading/index.module.scss
  src/app/components/Heading/index.stories.tsx
  src/app/components/Heading/index.tsx
Labels: enhancement

#2088 Feat/2236012071 tabs atomic component
  src/app/components/BorrowActivity/index.tsx
  src/app/components/Tab/index.tsx
  src/app/components/Tabs/index.stories.tsx
  src/app/components/Tabs/index.tsx
  src/app/components/UserAssets/VestedAssets.tsx
  src/app/components/UserAssets/index.tsx
  src/app/containers/WalletPage/index.tsx
Labels: refactoring

#2113 fix: change rpc for ethereum network
  src/app/pages/BridgeDepositPage/dictionaries/bridge-network-dictionary.ts
Labels: hotfix
