Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2022-06, with the labels that each got.

#2230 feat(btcs): change testnet contracts to support gsn
  src/app/pages/FastBtcPage/config/contracts.ts
Labels: enhancement

#2239 Perpetuals - bug fixes vol. 3
  src/app/pages/PerpetualPage/components/LeverageSelector/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/components/TradeFormStep.tsx
  src/app/pages/PerpetualPage/components/OpenOrdersTable/components/OpenOrderRow.tsx
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
  src/app/pages/PerpetualPage/hooks/usePerpetual_calculateResultingPosition.ts
  src/app/pages/PerpetualPage/utils/contractUtils.tsx
Labels: bug

#2233 New perpetuals competition branch
  src/app/components/HeaderLabs/index.tsx
  src/app/components/LinkToExplorer/index.tsx
  src/app/hooks/useIntersection.ts
  src/app/index.tsx
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/TraderRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.module.scss
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/types.ts
  src/app/pages/PerpetualPage/components/PairSelector/index.tsx
  src/app/pages/PerpetualPage/hooks/graphql/useGetLeaderboardData.ts
  src/locales/en/translation.json
  src/utils/classifiers.ts
  src/utils/dictionaries/perpetual-pair-dictionary.ts
Labels: enhancement

#2241 [Portis] - fix transactions issue
  package.json
  yarn.lock
Labels: release

#2244 Feat/2714824791 replace banner
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/pages/LandingPage/components/Banner/GetStartedBanner.tsx
  src/assets/images/banner/banner_zero.svg
  src/assets/images/banner/banner_zero_mobile.svg
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement, hotfix

#2248 Feat/2563153145 fouryear vesting
  src/app/components/UserAssets/Vesting/VestingWithdrawForm.tsx
  src/app/components/UserAssets/Vesting/types.ts
  src/app/components/UserAssets/Vesting/useListOfUserVestings.ts
  src/app/containers/StakePage/components/CurrentVests.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/components/WithdrawVesting.tsx
  src/app/containers/VestedHistory/index.tsx
  src/app/hooks/staking/useGetUnlockedVesting.ts
  src/app/hooks/staking/useVesting_getFourYearVesting.ts
  src/locales/en/translation.json
  src/utils/blockchain/abi/FourYearVesting.json
  src/utils/blockchain/abi/VestingRegistry.json
  src/utils/blockchain/requests/vesting.ts
Labels: release

#2252 feat: trezor eip712
  package.json
  yarn.lock
Labels: dependencies

#2214 Fix/repay borrow
  src/app/containers/RepayPositionHandler/RepayPositionForm.tsx
  src/locales/en/translation.json
  src/utils/classifiers.ts
Labels: bug, enhancement, hotfix

#2257 Remove FAQ / new sovrynProtcol ABI
  src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/locales/pt_br/translation.json
  src/utils/blockchain/abi/sovrynProtocol.json
Labels: enhancement, hotfix

#2224 [Portfolio] - the list of incoming changes:
  src/app/components/SovGenerationNFTS/index.tsx
  src/app/components/TransactionDialog/index.tsx
  src/app/components/UserAssets/TxDialog/WalletLogo.tsx
  src/app/components/UserAssets/TxDialog/dialog.module.scss
  src/app/components/UserAssets/TxDialog/index.tsx
  src/app/components/UserAssets/Vesting/VestingWithdrawForm.tsx
  src/app/components/UserAssets/components/BridgeLink.tsx
  src/app/components/UserAssets/components/ConversionDialog.tsx
  src/app/components/UserAssets/components/ConversionDialogContent.tsx
  src/app/components/UserAssets/components/UnWrapDialog.tsx
  src/app/components/UserAssets/components/UserAssetsTableRow.tsx
  src/app/components/UserAssets/components/VestedAssets.tsx
  src/app/components/UserAssets/index.module.scss
  src/app/components/UserAssets/index.tsx
  src/app/components/UserAssets/styled.ts
  src/app/containers/VestedHistory/components/VestedHistoryTable.tsx
  src/app/containers/VestedHistory/components/VestedHistoryTableRow.tsx
  src/app/containers/VestedHistory/index.tsx
  src/app/containers/WalletConnector/index.tsx
  src/app/containers/WalletPage/_overlay.scss
  src/app/containers/WalletPage/components/OriginClaimBanner.tsx
  src/app/containers/WalletPage/components/OriginClaimDialog.tsx
  src/app/containers/WalletPage/components/arrow-down.svg
  src/app/containers/WalletPage/components/dialog.module.scss
  src/app/containers/WalletPage/index.tsx
  src/app/index.tsx
  src/app/pages/PortfolioPage/Loadable.tsx
  src/app/pages/PortfolioPage/components/OriginClaimBanner.tsx
  src/app/pages/PortfolioPage/components/OriginClaimDialog.tsx
  src/app/pages/PortfolioPage/components/TopUpHistory.tsx
  src/app/pages/PortfolioPage/index.tsx
  src/app/pages/PortfolioPage/types.ts
  src/app/pages/RewardPage/index.tsx
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement

#2261 chore: change perpetual contract addresses
  src/app/pages/PerpetualPage/types.ts
  src/locales/en/translation.json
  src/utils/blockchain/contracts.testnet.ts
Labels: enhancement

#2209 feat(xusd): swap xusd amm pool contracts
  src/app/components/AssetValue/types.ts
  src/app/components/PairNavbar/Pair.tsx
  src/app/containers/SwapFormContainer/components/SwapSelector/index.tsx
  src/app/pages/BridgeDepositPage/dictionaries/assets/eth-to-rsk.testnet.ts
  src/app/pages/BridgeDepositPage/dictionaries/assets/rsk-to-bsc.testnet.ts
  src/app/pages/BridgeDepositPage/dictionaries/assets/rsk-to-eth.testnet.ts
  src/types/asset.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/dictionaries/amm/testnet.ts
  src/utils/dictionaries/assets-dictionary.ts
  src/utils/dictionaries/lending-pool-dictionary.ts
  src/utils/dictionaries/trading-pair-dictionary.ts
Labels: enhancement

#2263 feat: add perps comp popup
  public/index.html
Labels: enhancement

#2240 [Promotions] - move promotions to the its own component
  src/app/components/FinanceV2Components/LootDrop/LootDropSectionWrapper/index.tsx
  src/app/components/FinanceV2Components/LootDrop/index.tsx
  src/app/components/FinanceV2Components/LootDrop/styled.ts
  src/app/components/Promotions/components/PromotionCard/index.module.scss
  src/app/components/Promotions/components/PromotionCard/index.tsx
  src/app/components/Promotions/components/PromotionCard/types.ts
  src/app/components/Promotions/components/PromotionCard/utils.tsx
  src/app/components/Promotions/components/PromotionsCarousel/CustomDot.tsx
  src/app/components/Promotions/components/PromotionsCarousel/CustomLeftArrow.tsx
  src/app/components/Promotions/components/PromotionsCarousel/CustomRightArrow.tsx
  src/app/components/Promotions/components/PromotionsCarousel/index.module.scss
  src/app/components/Promotions/components/PromotionsCarousel/index.tsx
  src/app/components/Promotions/index.module.scss
  src/app/components/Promotions/index.tsx
  src/app/components/StakingDateSelector/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/pages/BorrowPage/index.tsx
  src/app/pages/LandingPage/components/Promotions/index.tsx
  src/app/pages/LandingPage/index.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/index.tsx
  src/app/pages/LendingPage/components/LendingDialog/index.tsx
  src/app/pages/LendingPage/index.tsx
  src/app/pages/LendingPage/types.ts
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/types.ts
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/MarginTradePage/index.tsx
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
  src/locales/en/translation.json
  src/utils/classifiers.ts
  src/utils/dictionaries/amm/mainnet.ts
  src/utils/dictionaries/amm/testnet.ts
  src/utils/models/amm-liquidity-pool.ts
  tailwind.config.js
Labels: enhancement

#2262 feat: add ZUSD to dapp, QoL changes to Portfolio
  src/app/components/AssetValue/types.ts
  src/app/components/SovGenerationNFTS/index.tsx
  src/app/components/UserAssets/Vesting/VestedItem.tsx
  src/app/components/UserAssets/components/BridgeLink.module.scss
  src/app/components/UserAssets/components/BridgeLink.tsx
  src/app/components/UserAssets/components/UserAssetsTableRow.tsx
  src/app/components/UserAssets/index.tsx
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/index.tsx
  src/app/pages/BridgeDepositPage/components/ReturnToPortfolio/index.tsx
  src/app/pages/BridgeDepositPage/index.tsx
  src/app/pages/BridgeWithdrawPage/components/ConfirmStep/index.tsx
  src/app/pages/BridgeWithdrawPage/components/SidebarSteps/index.tsx
  src/app/pages/BridgeWithdrawPage/index.tsx
  src/app/pages/FastBtcPage/components/Deposit/SidebarStepsDeposit.tsx
  src/app/pages/FastBtcPage/components/Deposit/StatusScreen.tsx
  src/app/pages/FastBtcPage/components/FastBtcHeader.tsx
  src/app/pages/FastBtcPage/components/Withdraw/SidebarStepsWithdraw.tsx
  src/app/pages/FastBtcPage/components/Withdraw/StatusScreen.tsx
  src/app/pages/FastBtcPage/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/ImportantInformationStep/index.tsx
  src/app/pages/PortfolioPage/index.tsx
  src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
  src/assets/images/tokens/zusd.svg
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/locales/pt_br/translation.json
  src/types/asset.ts
  src/utils/blockchain/abi/ZUSDToken.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/assets-dictionary.ts
Labels: enhancement

#2266 fix: broken menu URLs
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/utils/classifiers.ts
Labels: hotfix

#2271 Feat/2822193594 qol said the raven
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/WalletConnector/index.module.scss
  src/app/containers/WalletConnector/index.tsx
  src/utils/helpers.ts
Labels: enhancement, hotfix

#2276 Fix/2829091249 chunk chart data
  src/app/components/TradingChart/datafeed.ts
  src/app/index.tsx
Labels: bug, hotfix

#2277 Chunk Data requests (#2276), PT_BR localizations (#2268)
  src/app/components/TradingChart/datafeed.ts
  src/app/index.tsx
  src/locales/pt_br/translation.json
Labels: release

#2278 feat: netlify config
  netlify.toml
  package.json
  yarn.lock
Labels: enhancement

#2274 feat: add extra rel attribute to favicon for metamask "connected sites"
  public/index.html
Labels: enhancement

#2251 [BorrowPage] - replace borrow history endpoint with graphql
  package.json
  src/app/containers/BorrowHistory/hooks/useGetBorrowHistoryData.ts
  src/app/containers/BorrowHistory/index.tsx
  src/utils/graphql/README.md
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getBorrowHistory.graphql
  src/utils/graphql/rsk/schema.graphql
Labels: enhancement

#2289 [Spot] - remove unused component
  src/app/pages/SpotTradingPage/components/PriceHistory/index.tsx
Labels: refactoring

#2293 fix: zusd pricefeed console errors
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/utils/dictionaries/assets-dictionary.ts
Labels: bug

#2297 chore: update DisplayDate component display format
  src/app/components/ActiveUserLoanContainer/components/DisplayDate/index.tsx
  src/app/components/UserAssets/TxDialog/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/BuyStep/components/BuyDialog/components/TxDialog/index.tsx
  src/app/pages/PerpetualPage/components/ClosedPositionsTable/ClosedPositionRow.tsx
  src/app/pages/PerpetualPage/components/FundingPaymentsTable/FundingPaymentsRow.tsx
  src/app/pages/PerpetualPage/components/OpenOrdersTable/components/OpenOrderRow.tsx
  src/app/pages/PerpetualPage/components/OrderHistoryTable/OrderHistoryRow.tsx
Labels: refactoring

#2246 chore: change btcs token and aggregator contract
  src/app/pages/FastBtcPage/config/contracts.ts
Labels: enhancement

#2288 Add Zero to TVL stats
  src/app/containers/StatsPage/types.ts
  src/app/pages/LandingPage/components/TotalValueLocked/index.tsx
  src/app/pages/LandingPage/index.tsx
  src/locales/en/translation.json
  src/utils/blockchain/abi/StabilityPool.json
  src/utils/blockchain/abi/TroveManager.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
Labels: enhancement

#2300 Add Zero to TVL stats (#2288)
  src/app/containers/StatsPage/types.ts
  src/app/pages/LandingPage/components/TotalValueLocked/index.tsx
  src/app/pages/LandingPage/index.tsx
  src/locales/en/translation.json
  src/utils/blockchain/abi/StabilityPool.json
  src/utils/blockchain/abi/TroveManager.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
Labels: hotfix

#2299 Perpetuals - close only limit orders
  src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
  src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
  src/app/pages/PerpetualPage/types.ts
  src/app/pages/PerpetualPage/utils/contractUtils.tsx
  src/locales/en/translation.json
Labels: enhancement
