Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2022-08, with the labels that each got.

#2351 Perpetuals - configuration updates
  src/app/pages/BridgeDepositPage/dictionaries/bridge-network-dictionary.ts
  src/app/pages/PerpetualPage/utils/contractUtils.tsx
  src/utils/blockchain/networks.json
  src/utils/classifiers.ts
  src/utils/metamaskHelpers.ts
Labels: enhancement

#2353 fix: perps banner
  src/assets/images/banner/Decentralized_Perpetual.svg
  src/assets/images/banner/Decentralized_Perpetual_Mobile.svg
Labels: bug, hotfix

#2345 Feat/2790678855 tiny loan position
  src/app/containers/RepayPositionHandler/RepayPositionForm.tsx
  src/app/hooks/trading/useCloseWithDepositIsTinyPosition.ts
  src/utils/classifiers.ts
Labels: enhancement

#2284 Feat/2753828948 stake graphql endpoint
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/StakePage/components/HistoryEventsTable/HistoryEventRow.tsx
  src/app/containers/StakePage/components/HistoryEventsTable/index.tsx
  src/app/containers/StakePage/components/StakePagination/index.tsx
  src/app/containers/StakePage/hooks/useGetStakeHistory.ts
  src/app/containers/StakePage/index.tsx
  src/app/containers/StakePage/utils/index.tsx
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getStakeHistory.graphql
Labels: enhancement

#2358 Changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2340 Update Cookie Consent bar and analytics Opt-out
  public/index.html
  src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
Labels: enhancement

#2359 fix: add margin to deposit cross chain
  src/app/pages/BridgeDepositPage/index.tsx
  src/app/pages/BridgeWithdrawPage/index.tsx
Labels: bug

#2314 chore: update sovrynProtcol ABI
  src/utils/blockchain/abi/sovrynProtocol.json
Labels: enhancement, do-not-merge!

#2360 chore: revert cookie consent
  public/index.html
  src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
Labels: refactoring

#2361 Changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2364 Fix/release reversions
  src/app/containers/StatsPage/components/TVL.tsx
  src/app/containers/StatsPage/components/TradingVolume.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/hooks/trading/useGetCryptoPairs.ts
  src/app/hooks/useGetTokenPrice.tsx
  src/app/pages/BuySovPage/components/InfoBar/index.tsx
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/app/pages/LandingPage/index.tsx
  src/utils/blockchain/abi/sovrynProtocol.json
Labels: bug, refactoring

#2366 Feat/cross chain amount truncation
  src/app/pages/BridgeDepositPage/components/ReviewStep/index.tsx
  src/app/pages/BridgeWithdrawPage/components/ReviewStep/index.tsx
  src/app/pages/FastBtcPage/components/Withdraw/ReviewScreen.tsx
  src/locales/pt_br/translation.json
Labels: copy, hotfix

#2349 Perpetuals - BTCB conversion
  src/app/components/AssetValue/types.ts
  src/app/components/TransactionDialog/index.tsx
  src/app/containers/Dialog/index.tsx
  src/app/hooks/useGsnCheckAndApprove.ts
  src/app/pages/PerpetualPage/components/AccountBalanceForm/components/BTCBConversionDialog/index.module.scss
  src/app/pages/PerpetualPage/components/AccountBalanceForm/components/BTCBConversionDialog/index.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceForm/hooks/useConvertToBTCS.ts
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/assets/images/swap_vertical.svg
  src/locales/en/translation.json
  src/store/global/transactions-store/types.ts
  src/types/asset.ts
  src/utils/blockchain/abi/Masset.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
Labels: enhancement

#2372 Change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2370 Formatting fixes
  src/app/pages/FastBtcPage/components/Deposit/DepositDetails.tsx
  src/app/pages/RewardPage/components/LiquidTab/index.tsx
Labels: bug

#2374 Release 2022-08-05
  src/app/components/AssetValue/types.ts
  src/app/components/TransactionDialog/index.tsx
  src/app/containers/Dialog/index.tsx
  src/app/hooks/useGsnCheckAndApprove.ts
  src/app/pages/FastBtcPage/components/Deposit/DepositDetails.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceForm/components/BTCBConversionDialog/index.module.scss
  src/app/pages/PerpetualPage/components/AccountBalanceForm/components/BTCBConversionDialog/index.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceForm/hooks/useConvertToBTCS.ts
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/app/pages/RewardPage/components/LiquidTab/index.tsx
  src/assets/images/swap_vertical.svg
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  src/store/global/transactions-store/types.ts
  src/types/asset.ts
  src/utils/blockchain/abi/Masset.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
Labels: release

#2377 fix: margin trade contract call errors
  src/app/pages/MarginTradePage/components/AddToMarginDialog/index.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
Labels: bug

#2380 Perpetuals - Add bug bounty banner
  src/app/components/HeaderLabs/index.tsx
  src/app/containers/PageContainer/PageContainer.tsx
  src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
  src/app/containers/PageContainer/types.ts
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
  src/assets/images/Hacken.svg
  src/assets/images/perpetuals_bug_bounty.svg
Labels: enhancement

#2376 Changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2383 Changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2384 fix: FastBTC review screen value rounding
  src/app/pages/FastBtcPage/components/Deposit/StatusScreen.tsx
  src/app/pages/FastBtcPage/components/Withdraw/StatusScreen.tsx
Labels: bug

#2379 fix: margin trade profit contract call
  src/app/pages/MarginTradePage/components/OpenPositionsTable/ProfitContainer.tsx
Labels: bug

#2386 Release 2022-08-10
  src/app/components/HeaderLabs/index.tsx
  src/app/containers/PageContainer/PageContainer.tsx
  src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
  src/app/containers/PageContainer/types.ts
  src/app/pages/FastBtcPage/components/Deposit/StatusScreen.tsx
  src/app/pages/FastBtcPage/components/Withdraw/StatusScreen.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/ProfitContainer.tsx
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
  src/assets/images/Hacken.svg
  src/assets/images/perpetuals_bug_bounty.svg
  src/locales/pt_br/translation.json
Labels: release

#2368 chore: new sovrynProtocol abi for margin trading
  src/utils/blockchain/abi/sovrynProtocol.json
Labels: enhancement, do-not-merge!

#2369 chore: new RBTCWrapperProxy addresses and ABI
  src/utils/blockchain/abi/RBTCWrapperProxy.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
Labels: enhancement, do-not-merge!

#2385 Minor change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2388 Release 2022-08-11
  netlify.toml
  src/locales/pt_br/translation.json
  src/utils/blockchain/abi/RBTCWrapperProxy.json
  src/utils/blockchain/abi/sovrynProtocol.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
Labels: release

#2387 Fix/get dollar value
  src/app/hooks/trading/useGetProfitDollarValue.ts
Labels: bug

#2390 hotfix: margin trading pln calculation
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
Labels: bug, hotfix

#2391 Remove rWallet and Nifty
  package.json
  yarn.lock
Labels: enhancement

#2393 Release 16.08.2022
  package.json
  src/app/hooks/trading/useGetProfitDollarValue.ts
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
  src/locales/pt_br/translation.json
  yarn.lock
Labels: release

#2211 [Maintenance] - update maintenance url
  src/app/hooks/useMaintenance.ts
  src/locales/pt_br/translation.json
  src/store/global/maintenance-store/saga.ts
  src/store/global/maintenance-store/types.ts
  src/utils/classifiers.ts
Labels: enhancement

#2394 Release 2022-08-17
  src/app/hooks/useMaintenance.ts
  src/locales/pt_br/translation.json
  src/store/global/maintenance-store/saga.ts
  src/store/global/maintenance-store/types.ts
  src/utils/classifiers.ts
Labels: release

#2392 Perpetuals - adjust AMM Depth chart
  package.json
  src/app/pages/PerpetualPage/components/AmmDepthChart/AmmDepthChartRow.tsx
  src/app/pages/PerpetualPage/contexts/PerpetualQueriesContext.tsx
  yarn.lock
Labels: enhancement

#2356 Perpetuals - new rankings
  .env.local
  .env.mainnet.local
  .env.production
  .env.testnet
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/TraderRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/BestReturnTable/components/Header.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/BestReturnTable/components/TraderRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/BestReturnTable/hooks/useGetData.ts
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/BestReturnTable/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestProfitTable/components/Header.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestProfitTable/components/TraderRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestProfitTable/hooks/useGetData.ts
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestProfitTable/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestVolumeTable/components/Header.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestVolumeTable/components/TraderRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestVolumeTable/hooks/useGetData.ts
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/HighestVolumeTable/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/MostTradesTable/components/Header.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/MostTradesTable/components/TraderRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/MostTradesTable/hooks/useGetData.ts
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/MostTradesTable/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/Row/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/Table/index.module.scss
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/components/Table/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/hooks/useGetTimeRestrictedData.ts
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/types.ts
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/utils.ts
  src/app/pages/PerpetualPage/components/CompetitionPage/types.ts
  src/app/pages/PerpetualPage/hooks/graphql/useGetLeaderboardData.ts
  src/app/pages/PerpetualPage/hooks/graphql/useGetRealizedPnlData.ts
  src/locales/en/translation.json
  src/utils/classifiers.ts
Labels: enhancement

#2397 feat: update promotions
  src/app/components/Promotions/components/PromotionsCarousel/index.tsx
  src/app/components/Promotions/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  src/utils/dictionaries/amm/mainnet.ts
  src/utils/dictionaries/amm/testnet.ts
Labels: enhancement

#2396 Feat/2946022453 cookie consent bar
  public/index.html
  src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
Labels: enhancement

#2398 Release 2022-08-22
  public/index.html
  src/app/components/Promotions/components/PromotionsCarousel/index.tsx
  src/app/components/Promotions/index.tsx
  src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  src/utils/dictionaries/amm/mainnet.ts
  src/utils/dictionaries/amm/testnet.ts
Labels: release

#2401 [Reward] - update text note in liquidClaimForm tab
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement

#2402 [Portfolio] - fix table header (when no data)
  src/app/containers/VestedHistory/index.tsx
Labels: bug
