Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2022-02, with the labels that each got.

#2012 Add new strings and translate to PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#1873 Changes PT-BR
  src/locales/pt_br/translation.json
Labels: copy, stale

#2014 Fix leverage selector and max trade size
  src/app/pages/PerpetualPage/components/LeverageSelector/index.tsx
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
  src/app/pages/PerpetualPage/hooks/usePerpetual_queryPerpParameters.ts
  src/app/pages/PerpetualPage/utils/perpMath.ts
  src/app/pages/PerpetualPage/utils/perpUtils.ts
  src/locales/en/translation.json
Labels: bug

#2025 Minor change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2008 fix: use single tx for reward claiming
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/types.ts
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/hooks/useClaimRewardSov.tsx
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
  src/app/pages/RewardPage/components/RewardTab/index.tsx
  src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
  src/app/pages/RewardPage/index.tsx
Labels: bug

#2028 fix: switch placement of 'buy' & 'deposit' buttons
  src/app/components/UserAssets/index.tsx
Labels: copy, release

#1986 add Vesting Fees withdraw in staking page.
  src/app/containers/StakePage/components/FeeBlock.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/index.tsx
  src/app/hooks/staking/useStaking_getAccumulatedFees.ts
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/blockchain/requests/staking.ts
Labels: enhancement

#2032 Minor change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2029 fix: hide unsupported wallets
  package.json
  src/app/containers/WalletProvider/index.tsx
  yarn.lock
Labels: bug

#2035 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2010 Feat/678 Perpetual Meta Transactions
  package.json
  src/app/components/NetworkRibbon/NetworkRibbon.tsx
  src/app/containers/WalletProvider/index.tsx
  src/app/containers/WalletProvider/saga.ts
  src/app/containers/WalletProvider/slice.ts
  src/app/containers/WalletProvider/types.ts
  src/app/hooks/useBridgeNetworkSendTx.ts
  src/app/hooks/useGsnCheckAndApprove.ts
  src/app/hooks/useGsnSendTx.ts
  src/app/hooks/useMaintenance.ts
  src/app/hooks/useSendContractTx.ts
  src/app/hooks/useSendToContractAddressTx.ts
  src/app/pages/BridgeDepositPage/dictionaries/bridge-network-dictionary.ts
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/GsnSwitch/GsnSwitch.tsx
  src/app/pages/PerpetualPage/components/PairSelector/index.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ApprovalStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ConfirmationStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ReviewStep.tsx
  src/app/pages/PerpetualPage/hooks/usePerpetual_depositMarginToken.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_executeTransaction.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_openTrade.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_withdrawAll.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_withdrawMarginToken.ts
  src/app/pages/PerpetualPage/saga.ts
  src/app/pages/PerpetualPage/types.ts
  src/locales/en/translation.json
  src/store/global/transactions-store/types.ts
  src/types/chain-id.ts
  src/utils/blockchain/rpc-node.ts
  src/utils/classifiers.ts
  src/utils/gsn/GsnNetwork.ts
  src/utils/gsn/GsnProvider.ts
  src/utils/gsn/SovrynWalletGsnProvider.ts
  yarn.lock
Labels: enhancement

#2043 [Storybook] add preview viewports and backgrounds
  .storybook/preview.js
Labels: enhancement

#2039 Minor change PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2045 fix: remove duplicate lockedSOV calculation
  src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
Labels: bug

#2050 Release 2022 02 15
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
  src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
  src/locales/en/translation.json
  src/utils/classifiers.ts
Labels: release

#2017 change minReturn with minEntryPrice
  src/app/hooks/trading/useApproveAndTrade.ts
  src/app/hooks/trading/useCloseWithDeposit.ts
  src/app/hooks/trading/useGetActiveLoans.ts
  src/app/hooks/trading/useGetLoan.ts
  src/app/hooks/trading/useMarginTrade.ts
  src/app/pages/BuySovPage/components/BuyForm/useSlippage.ts
  src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
  src/app/pages/MarginTradePage/components/TradeDialog/trading-dialog.helpers.ts
  src/locales/en/translation.json
  src/types/active-loan.ts
  src/utils/blockchain/abi/LoanTokenLogicStandard.json
  src/utils/blockchain/abi/LoanTokenLogicWrbtc.json
  src/utils/blockchain/abi/sovrynProtocol.json
  src/utils/classifiers.ts
  yarn.lock
Labels: enhancement

#2062 fix: remove NotificationForm from margin trade page
  src/app/components/NotificationForm/EmailNotificationButton/index.tsx
  src/app/components/NotificationForm/NotificationFormComponent/index.tsx
  src/app/components/NotificationForm/NotificationFormContainer/index.tsx
  src/app/pages/MarginTradePage/index.tsx
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/locales/pt_br/translation.json
Labels: release, hotfix

#2052 Header cleanup
  src/app/components/Header/index.module.scss
  src/app/components/Header/index.tsx
  src/app/components/Header/styled.ts
  src/app/containers/WalletConnector/index.tsx
Labels: refactoring

#2058 Welcome page cleanup
  src/app/pages/LandingPage/components/Banner/GetStartedBanner.tsx
  src/app/pages/LandingPage/components/Promotions/components/PromotionCard/index.module.scss
  src/app/pages/LandingPage/components/Promotions/components/PromotionCard/index.tsx
  src/app/pages/LandingPage/components/Promotions/components/PromotionCard/styled.ts
  src/app/pages/LandingPage/components/Promotions/components/PromotionsCarousel/CustomDot.tsx
  src/app/pages/LandingPage/components/Promotions/components/PromotionsCarousel/CustomLeftArrow.tsx
  src/app/pages/LandingPage/components/Promotions/components/PromotionsCarousel/CustomRightArrow.tsx
  src/app/pages/LandingPage/components/Promotions/components/PromotionsCarousel/index.module.scss
  src/app/pages/LandingPage/components/Promotions/components/PromotionsCarousel/index.tsx
  src/app/pages/LandingPage/components/Promotions/components/PromotionsCarousel/styled.ts
  src/app/pages/LandingPage/components/Promotions/index.module.scss
  src/app/pages/LandingPage/components/Promotions/index.tsx
  src/app/pages/LandingPage/components/Promotions/styled.ts
  src/app/pages/LandingPage/components/TotalValueLocked/DataRow.tsx
  src/app/pages/LandingPage/components/TotalValueLocked/styled.ts
  src/app/pages/LandingPage/components/TradingVolume/index.module.scss
  src/app/pages/LandingPage/components/TradingVolume/index.tsx
  src/app/pages/LandingPage/components/TradingVolume/styled.ts
  src/app/pages/LandingPage/index.module.scss
  src/app/pages/LandingPage/index.tsx
  src/app/pages/LandingPage/styled.ts
Labels: refactoring

#2048 Origins launchpad cleanup
  src/app/pages/OriginsLaunchpad/index.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCard/InfoRow.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCard/index.module.scss
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCard/index.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCard/styled.ts
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCardSection/index.module.scss
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCardSection/index.tsx
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCardSection/module.scss
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/PreviousSalesCardSection/styled.ts
  src/styles/global-styles.ts
  src/styles/sass/global.scss
  tailwind.config.js
Labels: refactoring

#2057 Feat/2273904016 fastbtc receiver
  package.json
  src/app/pages/FastBtcPage/components/Withdraw/AddressForm.tsx
  src/locales/en/translation.json
  yarn.lock
Labels: enhancement, FastBTC

#1995 Feat/perpetuals account
  .vscode/settings.json
  src/app/components/AssetValue/types.ts
  src/app/components/Dialogs/TxDialog.tsx
  src/app/components/Form/AmountInput/index.tsx
  src/app/components/LinkToExplorer/index.tsx
  src/app/hooks/useBridgeNetworkBalance.ts
  src/app/hooks/useChainToSendContractTx.ts
  src/app/hooks/useDebouncedEffect.ts
  src/app/pages/BridgeDepositPage/components/WalletSelector/index.tsx
  src/app/pages/FastBtcPage/components/AggregatorWithdraw/AmountForm.tsx
  src/app/pages/FastBtcPage/components/AggregatorWithdraw/AmountInput.tsx
  src/app/pages/FastBtcPage/components/AggregatorWithdraw/ConfirmationScreens.tsx
  src/app/pages/FastBtcPage/components/AggregatorWithdraw/NetworkStep.tsx
  src/app/pages/FastBtcPage/components/Deposit/SidebarStepsDeposit.tsx
  src/app/pages/FastBtcPage/components/Deposit/StatusScreen.tsx
  src/app/pages/FastBtcPage/components/Withdraw/ConfirmationScreens.tsx
  src/app/pages/FastBtcPage/components/Withdraw/ReviewScreen.tsx
  src/app/pages/FastBtcPage/components/Withdraw/SidebarStepsWithdraw.tsx
  src/app/pages/FastBtcPage/components/Withdraw/StatusScreen.tsx
  src/app/pages/FastBtcPage/components/Withdraw/WithdrawDetails.tsx
  src/app/pages/FastBtcPage/config/contracts.ts
  src/app/pages/FastBtcPage/containers/AggregatorWithdrawContainer.tsx
  src/app/pages/FastBtcPage/containers/DepositContainer.tsx
  src/app/pages/FastBtcPage/containers/WithdrawContainer.tsx
  src/app/pages/FastBtcPage/contexts/withdraw-context.ts
  src/app/pages/FastBtcPage/hooks/useWithdrawBridgeConfig.ts
  src/app/pages/FastBtcPage/index.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceCard/index.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/locales/en/translation.json
  src/utils/blockchain/abi/fastBtcBridge.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
Labels: enhancement

#2047 [Spinner] - update spinner
  src/app/components/Spinner/index.module.scss
  src/app/components/Spinner/index.stories.tsx
  src/app/components/Spinner/index.tsx
  src/app/components/Spinner/types.ts
  tailwind.config.js
Labels: refactoring

#2066 Prevent re-toasting
  src/app/pages/PerpetualPage/components/ToastsWatcher/index.tsx
  src/app/pages/PerpetualPage/slice.ts
  src/app/pages/PerpetualPage/types.ts
  src/app/pages/PerpetualPage/utils/perpMath.ts
Labels: enhancement

#2063 Refactor duplicated carousels
  package.json
  src/app/components/StakingDateSelector/CustomArrow.tsx
  src/app/components/StakingDateSelector/CustomButtonGroup.tsx
  src/app/components/StakingDateSelector/index.tsx
  src/styles/tailwindcss/components.css
  yarn.lock
Labels: refactoring
