Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2022-09, with the labels that each got.

#2405 feat: update XUSD lend pool rewards
  README.md
  src/app/components/Promotions/index.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
  src/app/pages/LendingPage/index.tsx
Labels: enhancement

#2406 Release 2022-09-05
  README.md
  src/app/components/Promotions/index.tsx
  src/app/containers/VestedHistory/index.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
  src/app/pages/LendingPage/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  yarn.lock
Labels: release

#2382 Fix/migration deployment fix
  src/app/components/PairNavbar/PairCryptocurrency.tsx
  src/app/components/PairNavbar/PairLabels.tsx
  src/app/components/PairNavbar/index.tsx
  src/app/components/PairNavbarInfo/index.tsx
  src/app/containers/StatsPage/components/TVL.tsx
  src/app/containers/StatsPage/components/TradingVolume.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/hooks/trading/useGetCryptoPairs.ts
  src/app/hooks/useGetTokenPrice.tsx
  src/app/pages/BuySovPage/components/InfoBar/index.tsx
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/app/pages/LandingPage/index.tsx
Labels: bug

#2410 Update PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2294 [Spot, Margin] - Replace RPC usage for events spot & margin pages
  src/app/pages/MarginTradePage/components/LimitOrder/LimitOrderRow/index.tsx
  src/app/pages/MarginTradePage/hooks/useGetLimitOrderEvents.ts
  src/app/pages/MarginTradePage/hooks/useGetMarginLimitOrderFilled.ts
  src/app/pages/MarginTradePage/index.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/LimitOrderHistory/index.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/LimitOrderRow.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/OpenPositionsTable/index.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/index.tsx
  src/app/pages/SpotTradingPage/hooks/useGetLimitOrderCreated.ts
  src/app/pages/SpotTradingPage/hooks/useGetLimitOrderFilled.ts
  src/locales/pt_br/translation.json
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getLimitOrderCreated.graphql
  src/utils/graphql/rsk/operations/getLimitOrderFilled.graphql
  src/utils/graphql/rsk/operations/getMarginLimitOrderFilled.graphql
  src/utils/graphql/rsk/schema.graphql
Labels: enhancement, do-not-merge!

#2403 SOV-427: closing limit orders with hw
  src/app/hooks/useSendTx.ts
  src/utils/sovryn/sovryn-network.ts
Labels: bug

#2413 Hide perps banner on homepage
  src/app/pages/LandingPage/components/Banner/GetStartedBanner.tsx
Labels: enhancement

#2193 feat(chart): add graphql for trading chart
  README.md
  package.json
  src/app/components/PairNavbar/PairCryptocurrency.tsx
  src/app/components/PairNavbarInfo/index.tsx
  src/app/components/TradingChart/datafeed.ts
  src/app/components/TradingChart/dictionary.ts
  src/app/components/TradingChart/helpers.ts
  src/app/components/TradingChart/index.tsx
  src/app/components/TradingChart/streaming.ts
  src/app/components/TradingChart/types.ts
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/pages/MarginTradePage/components/OpenPositionsTable/PositionRow.tsx
  src/app/pages/MarginTradePage/slice.ts
  src/app/pages/PerpetualPage/components/TradingChart/helpers.ts
  src/app/pages/PerpetualPage/hooks/graphql/useGetCandles.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_ContractDetails.ts
  src/app/pages/SpotTradingPage/slice.ts
  src/locales/en/translation.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/classifiers.ts
  src/utils/pair-price-tracker.ts
  yarn.lock
Labels: enhancement

#2414 Added isLimit where clause to swap history
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getSwapHistory.graphql
Labels: bug, do-not-merge!, hotfix

#2418 switch Zero TVL contract calls with backend query
  src/app/pages/LandingPage/index.tsx
Labels: bug, hotfix

#2417 Feat/sov 554 perps shutdown
  README.md
  package.json
  src/app/components/PairNavbar/PairCryptocurrency.tsx
  src/app/components/PairNavbarInfo/index.tsx
  src/app/components/TradingChart/datafeed.ts
  src/app/components/TradingChart/dictionary.ts
  src/app/components/TradingChart/helpers.ts
  src/app/components/TradingChart/index.tsx
  src/app/components/TradingChart/streaming.ts
  src/app/components/TradingChart/types.ts
  src/app/containers/PageContainer/PageContainer.tsx
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/PositionRow.tsx
  src/app/pages/MarginTradePage/slice.ts
  src/app/pages/PerpetualPage/components/TradingChart/helpers.ts
  src/app/pages/PerpetualPage/hooks/graphql/useGetCandles.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_ContractDetails.ts
  src/app/pages/PerpetualsPlaceholderPage/Loadable.tsx
  src/app/pages/PerpetualsPlaceholderPage/index.module.css
  src/app/pages/PerpetualsPlaceholderPage/index.tsx
  src/app/pages/SpotTradingPage/slice.ts
  src/assets/images/perpetuals-shutdown/Discord.svg
  src/assets/images/perpetuals-shutdown/Logo.svg
  src/assets/images/perpetuals-shutdown/Telegram.svg
  src/assets/images/perpetuals-shutdown/Twitter.svg
  src/assets/images/perpetuals-shutdown/perpetuals_screenshot_without_header.png
  src/assets/perpetuals_screenshot_without_header.png
  src/locales/en/translation.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/classifiers.ts
  src/utils/pair-price-tracker.ts
  yarn.lock
Labels: enhancement

#2420 switch Zero TVL contract calls with backend query
  src/app/pages/LandingPage/index.tsx
Labels: bug, hotfix

#2424 Perpetuals shutdown page
  src/app/components/NetworkRibbon/NetworkRibbon.tsx
  src/app/containers/PageContainer/PageContainer.tsx
  src/app/index.tsx
  src/app/pages/PerpetualsPlaceholderPage/Loadable.tsx
  src/app/pages/PerpetualsPlaceholderPage/index.module.css
  src/app/pages/PerpetualsPlaceholderPage/index.tsx
  src/assets/images/perpetuals-shutdown/Discord.svg
  src/assets/images/perpetuals-shutdown/Logo.svg
  src/assets/images/perpetuals-shutdown/Telegram.svg
  src/assets/images/perpetuals-shutdown/Twitter.svg
  src/assets/images/perpetuals-shutdown/perpetuals_screenshot_without_header.png
  src/assets/perpetuals_screenshot_without_header.png
  src/locales/en/translation.json
  src/utils/classifiers.ts
Labels: enhancement

#2407 Feat/sov 476 perpetuals gas optimization deployment
  README.md
  package.json
  src/app/pages/PerpetualPage/components/TradingChart/helpers.ts
  src/app/pages/PerpetualPage/components/TradingChart/index.tsx
  src/app/pages/PerpetualPage/components/TradingChart/streaming.ts
  src/app/pages/PerpetualPage/contexts/RecentTradesContext.tsx
  src/app/pages/PerpetualPage/hooks/graphql/useGetCandles.ts
  src/app/pages/PerpetualPage/hooks/graphql/useGetTraderEvents.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_ClosedPositions.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_FundingPayments.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_OpenPositions.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_transaction.ts
  src/app/pages/PerpetualPage/types.ts
  src/app/pages/PerpetualPage/utils/contractUtils.tsx
  src/utils/blockchain/abi/PerpetualLimitOrderBook.json
  src/utils/blockchain/abi/PerpetualManager.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/classifiers.ts
  src/utils/dictionaries/perpetual-pair-dictionary.ts
  yarn.lock
Labels: WIP, do-not-merge!
