Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2022-01, with the labels that each got.

#1978 Fix Team SOV vesting history
  src/app/hooks/staking/useVesting_getTeamVesting.ts
Labels: bug, hotfix

#1988 fix(bridge): reset USDT allowance to 0
  src/app/pages/BridgeDepositPage/saga.ts
Labels: bug, hotfix

#1994 Master
  src/app/hooks/staking/useVesting_getTeamVesting.ts
  src/app/pages/BridgeDepositPage/saga.ts
Labels: exclude-from-release

#2004 chore: change contract ABI's
  src/utils/blockchain/abi/FeeSharingProxy.json
  src/utils/blockchain/abi/StakingRewards.json
  src/utils/blockchain/abi/bzxAbi.json
Labels: release

#1985 Feat/lending data attr
  src/app/components/ActiveBorrowTable/index.tsx
  src/app/components/FieldGroup/index.tsx
  src/app/components/Form/AmountInput/index.tsx
  src/app/components/InputField/index.tsx
  src/app/components/TradeButton/index.tsx
  src/app/containers/AmountField/index.tsx
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/CurrentVests.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/pages/BorrowPage/BorrowingContainer/index.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
  src/app/pages/LendingPage/components/LendingDialog/index.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/AddLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/RemoveLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/index.tsx
Labels: enhancement
