Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2022-10, with the labels that each got.

#2426 hotfix: switch to swap network
  package.json
  src/app/pages/SpotTradingPage/components/TradeForm/MarketForm.tsx
  yarn.lock
Labels: hotfix

#2428 Cleanup unused legacy backend references
  src/app/pages/LiquidityMining/hooks/useUserPoolData.ts
  src/app/pages/OriginsLaunchpad/pages/Dashboard/components/EmailSubscribeSection/index.tsx
Labels: refactoring

#2415 SOV-543: recent trades on graphql
  src/app/components/AssetValue/index.tsx
  src/app/components/RecentTrades/RecentSwapRow.tsx
  src/app/components/RecentTrades/RecentTradeRow.tsx
  src/app/hooks/trading/useMargin_RecentTrades.ts
  src/app/hooks/trading/useSwap_RecentTrades.ts
  src/types/trading-pairs.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/dictionaries/amm/testnet.ts
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getRecentMarginEvents.graphql
  src/utils/graphql/rsk/operations/getRecentSwapEvents.graphql
  src/utils/helpers.ts
Labels: enhancement

#2429 fix: outdated usage of "allow tokens" contract in bridge
  src/app/pages/BridgeDepositPage/dictionaries/bridges/mainnet.ts
  src/app/pages/BridgeDepositPage/hooks/useBridgeLimits.ts
  src/app/pages/BridgeDepositPage/types/bridge-model.ts
Labels: bug

#2435 chore: increase suggested gas limit for adding AMM liquidity
  src/utils/classifiers.ts
Labels: hotfix

#2437 feat: disable RBTC fee claiming on Rewards page
  src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
  src/app/pages/RewardPage/components/FeesEarnedTab/index.tsx
Labels: hotfix

#2434 Trading pair rates migration
  src/app/hooks/price-feeds/usePriceFeeds_tradingPairRates.ts
  src/app/hooks/trading/useGetProfitDollarValue.ts
  src/app/hooks/useDollarValue.ts
  src/app/index.tsx
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/PositionRow.tsx
  src/utils/classifiers.ts
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getTokenRates.graphql
Labels: enhancement, do-not-merge!

#2433 SOV-779: add memory caching to blockchain call hooks
  package.json
  src/app/components/Icon/index.tsx
  src/app/containers/StakePage/components/HistoryEventsTable/index.tsx
  src/app/hooks/chain/useCacheCallTo.ts
  src/app/hooks/useAssetBalanceOf.ts
  src/app/hooks/useBalance.ts
  src/app/hooks/useCacheCall.ts
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/utils/blockchain/cache.ts
  src/utils/sovryn/contract-reader.ts
  yarn.lock
Labels: enhancement

#2441 fix: switchNetwork BSC issue
  src/app/pages/BridgeDepositPage/components/WalletSelector/index.tsx
  src/app/pages/FastBtcPage/components/AggregatorWithdraw/NetworkStep.tsx
  src/utils/metamaskHelpers.ts
Labels: hotfix

#2445 chore: fix analytics visit tracking with no GA id
  src/app/containers/WalletProvider/saga.ts
Labels: bug

#2448 feat: enable RBTC fee claiming in Rewards page
  src/app/pages/RewardPage/components/FeesEarnedTab/index.tsx
Labels: enhancement, hotfix

#2452 fix: trading chart layout on mobile
  src/app/components/TradingChart/index.tsx
Labels: bug, hotfix

#2453 chore: re-enable rbtc fee claiming
  src/app/pages/RewardPage/components/FeesEarnedTab/index.tsx
Labels: hotfix

#2454 SOV-962 - chore: bump gaslimit for adding to lend pool txs
  src/utils/classifiers.ts
Labels: hotfix
