Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2022-07, with the labels that each got.

#2302 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2164 feat: mainnet contracts for btc <-> btcs
  .env.mainnet.local
  src/app/pages/FastBtcPage/config/contracts.ts
  src/app/pages/FastBtcPage/hooks/useWithdrawBridgeConfig.ts
Labels: enhancement

#2306 feat: update XUSD lend pool reward promo
  src/locales/en/translation.json
Labels: enhancement, hotfix

#2309 Master to dev 2022 07 04
  .env.local
  .env.mainnet.local
  .env.testnet
  package.json
  public/index.html
  src/app/components/HeaderLabs/index.tsx
  src/app/components/OptOutDialog/index.tsx
  src/app/containers/PageContainer/PageContainer.tsx
  src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
  src/app/containers/WalletProvider/index.tsx
  src/app/hooks/useAnalytics.ts
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  yarn.lock
Labels: release

#2311 Fix/limit order maintenance
  src/app/hooks/useMaintenance.ts
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
Labels: bug, hotfix

#2304 Perpetuals - add data action ids
  src/app/components/Input/index.tsx
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceCard/index.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/app/pages/PerpetualPage/components/GsnSwitch/GsnSwitch.tsx
  src/app/pages/PerpetualPage/components/LayoutMenu/index.tsx
  src/app/pages/PerpetualPage/components/LeverageSelector/index.tsx
  src/app/pages/PerpetualPage/components/OpenOrdersTable/components/OpenOrderRow.tsx
  src/app/pages/PerpetualPage/components/OpenPositionsTable/components/OpenPositionRow.tsx
  src/app/pages/PerpetualPage/components/PairSelector/PairSelectorButton.tsx
  src/app/pages/PerpetualPage/components/TableRowAction/index.tsx
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
Labels: enhancement

#2312 Perpetuals - final fixes before mainnet competition
  src/app/pages/PerpetualPage/components/AccountBalanceCard/index.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/app/pages/PerpetualPage/components/AmmDepthChart/AmmDepthChartRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/TradeSummary.tsx
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
  src/utils/metamaskHelpers.ts
Labels: enhancement

#2321 Perpetuals - adjust subgraph healtcheck + fix errors
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
  src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
Labels: bug

#2322 Perpetuals - adjust subgraph healtcheck + fix errors (#2321)
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
  src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
Labels: hotfix

#2324 Perpetuals - update websockets and RPC configuration (#2323)
  src/app/pages/BridgeDepositPage/dictionaries/bridge-network-dictionary.ts
  src/utils/blockchain/networks.json
  src/utils/classifiers.ts
  src/utils/metamaskHelpers.ts
Labels: hotfix

#2326 Perpetuals - temporary change of testnet bridge link
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
Labels: bug

#2331 Release 2022-07-13
  src/app/hooks/useGsnSendTx.ts
  src/app/hooks/useSendContractTx.ts
  src/app/pages/FastBtcPage/containers/DepositContainer.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ConfirmationStep.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  src/store/global/transactions-store/types.ts
Labels: release

#2334 Perpetuals - remove whitelist (#2332)
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/RegisterDialog/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/components/ConnectFormStep.tsx
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
  src/app/pages/PerpetualPage/hooks/usePerpetual_isAddressWhitelisted.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_transaction.ts
  src/locales/en/translation.json
Labels: release

#2307 [Portfolio] - add data-ids attr
  src/app/components/UserAssets/Vesting/VestedItem.tsx
  src/app/components/UserAssets/Vesting/VestingWithdrawForm.tsx
  src/app/components/UserAssets/components/BridgeLink.tsx
  src/app/components/UserAssets/components/UserAssetsTableRow.tsx
  src/app/pages/PortfolioPage/index.tsx
Labels: enhancement

#2335 Perpetuals - competition countdown
  package.json
  src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/CompetitionEndCountdown/index.tsx
  src/locales/en/translation.json
  yarn.lock
Labels: enhancement

#2338 Perpetuals - Show potential competition prizes
  package.json
  src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/TraderRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
  src/app/pages/PerpetualPage/hooks/usePerpetual_getAmmCompetitionProfit.ts
  src/locales/en/translation.json
  src/utils/blockchain/abi/lpShareToken.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  yarn.lock
Labels: enhancement

#2339 Release 2022-07-15
  package.json
  src/app/components/UserAssets/Vesting/VestedItem.tsx
  src/app/components/UserAssets/Vesting/VestingWithdrawForm.tsx
  src/app/components/UserAssets/components/BridgeLink.tsx
  src/app/components/UserAssets/components/UserAssetsTableRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/CompetitionEndCountdown/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/TraderRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/components/ConnectFormStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ReviewStep.tsx
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
  src/app/pages/PerpetualPage/hooks/usePerpetual_getAmmCompetitionProfit.ts
  src/app/pages/PortfolioPage/index.tsx
  src/locales/en/translation.json
  src/utils/blockchain/abi/lpShareToken.json
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  yarn.lock
Labels: release

#2341 Perpetuals - fix 24h volume bug
  src/app/pages/PerpetualPage/hooks/usePerpetual_ContractDetails.ts
Labels: bug

#2342 Release
  src/app/pages/PerpetualPage/hooks/usePerpetual_ContractDetails.ts
Labels: release

#2344 Perpetuals - UI changes for end of the mainnet competition
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/TraderRow.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
  src/app/pages/PerpetualPage/components/CompetitionPage/components/RegisterDialog/index.tsx
  src/locales/en/translation.json
Labels: enhancement, do-not-merge!

#2303 [Lending] - replace legacy backend endpoint usage for Lending APY his…
  src/app/components/LoanTokenGraphs/index.tsx
  src/app/components/LoanTokenGraphs/types.ts
  src/app/hooks/lending/useGetLendingHistory.ts
  src/app/pages/LendingPage/components/CurrencyContainer/PoolChart.tsx
  src/utils/classifiers.ts
Labels: enhancement, do-not-merge!

#2290 2753851238 lend history endpoint migration
  src/app/pages/LendingPage/components/HistoryTable/TableBody/index.tsx
  src/app/pages/LendingPage/components/HistoryTable/TableRow/index.tsx
  src/app/pages/LendingPage/components/HistoryTable/index.tsx
  src/app/pages/LendingPage/hooks/useGetLendingHistoryData.ts
  src/app/pages/LendingPage/types.ts
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getLendHistory.graphql
  src/utils/graphql/rsk/schema.graphql
Labels: enhancement, do-not-merge!

#2327 [Reward] - update reward endpoint part 2
  README.md
  src/app/pages/RewardPage/components/FeesEarnedTab/index.tsx
  src/app/pages/RewardPage/components/RewardTab/hooks/useGetAvailableTradingRewards.ts
  src/app/pages/RewardPage/components/RewardTab/hooks/useGetTotalTradingRewards.ts
  src/app/pages/RewardPage/components/RewardTab/hooks/useGetTradingRewards.ts
  src/app/pages/RewardPage/components/RewardTab/index.tsx
  src/app/pages/RewardPage/components/RewardsDetail/index.tsx
  src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getTradingRewards.graphql
  src/utils/graphql/rsk/schema.graphql
Labels: enhancement

#2286 Feat/landing endpoint migration
  src/app/pages/LandingPage/components/AmmBalance/index.tsx
  src/app/pages/LiquidityMining/components/HistoryTable/TableBody/index.tsx
  src/app/pages/LiquidityMining/components/HistoryTable/index.tsx
  src/app/pages/LiquidityMining/components/MiningPool/PoolChart.tsx
  src/app/pages/LiquidityMining/components/MiningPool/UserPoolInfo.tsx
  src/app/pages/LiquidityMining/components/MiningPool/types.ts
  src/app/pages/LiquidityMining/components/RowTable/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/app/pages/RewardPage/components/HistoryTable/index.tsx
  src/utils/classifiers.ts
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/liquidityPool.graphql
Labels: enhancement, do-not-merge!

#2275 [Margin] - Replace legacy backend endpoint usage on Margin trade page…
  src/app/components/AssetValue/index.tsx
  src/app/components/TradeProfit/index.tsx
  src/app/pages/MarginTradePage/components/AddToMarginDialog/index.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
  src/app/pages/MarginTradePage/components/ClosedPositionsTable/ClosedPositionRow.tsx
  src/app/pages/MarginTradePage/components/ClosedPositionsTable/index.tsx
  src/app/pages/MarginTradePage/components/MarginPagination/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/OpenPositionsTable.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/PositionRow.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/ProfitContainer.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/hooks/useMargin_getActiveLoans.ts
  src/app/pages/MarginTradePage/components/OpenPositionsTable/hooks/useMargin_getLoanEvents.ts
  src/app/pages/MarginTradePage/components/PositionEventsTable/PositionEventRow.tsx
  src/app/pages/MarginTradePage/components/PositionEventsTable/index.tsx
  src/app/pages/MarginTradePage/components/PositionEventsTable/utils.ts
  src/app/pages/MarginTradePage/hooks/useMargin_GetLoans.ts
  src/app/pages/MarginTradePage/types.ts
  src/app/pages/MarginTradePage/utils/marginUtils.ts
  src/locales/en/translation.json
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getMarginLoansData.graphql
Labels: enhancement

#2298 feat: migrate trading endpoints
  src/app/containers/StatsPage/components/TVL.tsx
  src/app/containers/StatsPage/components/TradingVolume.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/hooks/trading/useGetCryptoPairs.ts
  src/app/hooks/useGetTokenPrice.tsx
  src/app/pages/BuySovPage/components/InfoBar/index.tsx
  src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
  src/app/pages/LandingPage/index.tsx
  src/utils/classifiers.ts
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/token.graphql
Labels: enhancement, do-not-merge!

#2310 feat: migrate swap/spot history
  src/app/containers/SwapHistory/components/AssetRow.tsx
  src/app/containers/SwapHistory/index.tsx
  src/app/pages/SpotTradingPage/components/SpotHistory/AssetRow.tsx
  src/app/pages/SpotTradingPage/components/SpotHistory/index.tsx
  src/utils/graphql/README.md
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getSwapHistory.graphql
Labels: enhancement

#2329 [Portfolio] - replace endpoint
  src/app/containers/VestedHistory/components/VestedHistoryContracts.tsx
  src/app/containers/VestedHistory/components/VestedHistoryRow.tsx
  src/app/containers/VestedHistory/components/VestedHistoryTable.tsx
  src/app/containers/VestedHistory/components/VestedHistoryTableRow.tsx
  src/app/containers/VestedHistory/index.tsx
  src/app/containers/VestedHistory/utils.ts
  src/app/hooks/staking/useGetVestedHistory.ts
  src/app/hooks/staking/useVesting_getFourYearVesting.ts
  src/app/hooks/staking/useVesting_getOriginVesting.ts
  src/app/hooks/staking/useVesting_getRewards.ts
  src/app/hooks/staking/useVesting_getTeamVesting.ts
  src/app/pages/LiquidityMining/components/HistoryTable/index.tsx
  src/app/pages/RewardPage/components/HistoryTable/index.tsx
  src/utils/classifiers.ts
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getVestedHistory.graphql
Labels: enhancement
