Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2022-05, with the labels that each got.

#2167 fix: bump perpetuals lib version
  package.json
  yarn.lock
Labels: dependencies

#2170 fix: margin trading issues
  src/app/pages/BuySovPage/components/BuyForm/useSlippage.ts
  src/app/pages/MarginTradePage/components/TradeDialog/TradeDialogContent.tsx
  src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
Labels: bug

#2158 feat: enforce new checkboxs
  src/app/components/Checkbox/index.module.scss
  src/app/components/FirstVisitDisclaimerDialog/index.tsx
  src/app/components/MobileBrowsersWarningDialog/index.tsx
  src/app/components/OptOutDialog/index.tsx
  src/app/pages/MarginTradePage/components/TradeDialog/TradeDialogContent.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/ImportantInformationStep/index.tsx
  src/styles/sass/blueprint-override.scss
Labels: enhancement

#2175 Feat/hide margin limit
  src/app/components/OrderTypeTitle/index.tsx
  src/app/containers/SwapFormContainer/components/SwapStatsPrices/index.module.scss
  src/app/containers/SwapFormContainer/components/SwapStatsPrices/index.tsx
  src/app/containers/SwapFormContainer/index.module.scss
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/app/pages/MarginTradePage/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/LimitForm.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/MarketForm.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/index.module.scss
  src/assets/images/trend-arrow-up.svg
  src/locales/en/translation.json
Labels: refactoring

#2173 chore(deps): bump sovryn wallet version
  package.json
  yarn.lock
Labels: dependencies

#2169 [Rewards] - add data ids
  src/app/components/Form/ActionButton/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/LiquidClaimForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
  src/app/pages/RewardPage/components/Tab/index.tsx
  src/app/pages/RewardPage/index.tsx
Labels: enhancement

#2172 [Stake] - add data ids
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/index.tsx
Labels: enhancement

#2171 [Swap] - add data ids
  src/app/components/Arbitrage/Arbitrage.tsx
  src/app/containers/SwapFormContainer/components/SwapSelector/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
Labels: enhancement

#2150 feat: enforce tab component
  src/app/components/BorrowActivity/index.tsx
  src/app/pages/MarginTradePage/components/LimitOrder/LimitOrderHistory/index.tsx
  src/app/pages/MarginTradePage/components/LimitOrder/LimitOrderRow/index.tsx
  src/app/pages/MarginTradePage/components/LimitOrder/OpenLimitOrdersPositionsTable/index.tsx
  src/app/pages/MarginTradePage/hooks/useGetLimitOrderEvents.ts
  src/app/pages/MarginTradePage/index.tsx
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/SpotTradingPage/index.tsx
  src/locales/en/translation.json
Labels: enhancement

#2179 [Origins] - add data-id
  src/app/pages/OriginsClaimPage/components/ClaimForm/index.tsx
Labels: enhancement

#2165 Order History adjustments
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/ContractDetails/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/components/ConnectFormStep.tsx
  src/app/pages/PerpetualPage/components/OrderHistoryTable/OrderHistoryRow.tsx
  src/app/pages/PerpetualPage/components/OrderHistoryTable/index.tsx
  src/app/pages/PerpetualPage/hooks/graphql/useGetTraderEvents.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_OpenOrders.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_OrderHistory.ts
  src/app/pages/PerpetualPage/types.ts
  src/locales/en/translation.json
Labels: refactoring

#2162 feat: data attributes added
  src/app/components/FinanceV2Components/PieChart/styled.ts
  src/app/components/FormSelect/index.tsx
  src/app/components/LanguageToggle/index.tsx
  src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/pages/BuySovPage/components/Button/index.tsx
  src/app/pages/BuySovPage/components/EngageWallet/index.tsx
  src/app/pages/BuySovPage/components/Feature/index.tsx
  src/app/pages/BuySovPage/components/Features/StakeVote.tsx
  src/app/pages/BuySovPage/components/Features/index.tsx
  src/app/pages/BuySovPage/components/TopUpWallet/index.tsx
  src/app/pages/LandingPage/components/Banner/GetStartedBanner.tsx
  src/app/pages/LandingPage/components/Promotions/components/PromotionCard/index.tsx
Labels: enhancement

#2157 Feat/input component
  src/app/components/Input/InputBase.tsx
  src/app/components/Input/index.module.scss
  src/app/components/Input/index.stories.tsx
  src/app/components/Input/index.tsx
  src/app/pages/PerpetualPage/components/LeverageSelector/index.tsx
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
Labels: enhancement

#2177 Feat/spot recent trades
  package.json
  src/app/components/Arbitrage/Arbitrage.tsx
  src/app/components/Form/ActionButton/index.tsx
  src/app/components/PairNavbarInfo/index.tsx
  src/app/components/RecentTrades/MarginTrades.tsx
  src/app/components/RecentTrades/RecentSwapRow.tsx
  src/app/components/RecentTrades/SwapTrades.tsx
  src/app/components/RecentTrades/index.module.scss
  src/app/components/RecentTrades/index.tsx
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/index.tsx
  src/app/containers/SwapFormContainer/components/ReviewDialog/index.tsx
  src/app/containers/SwapFormContainer/components/SwapSelector/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/hooks/trading/useSwap_RecentTrades.ts
  src/app/pages/MarginTradePage/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/LiquidClaimForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
  src/app/pages/RewardPage/components/Tab/index.tsx
  src/app/pages/RewardPage/index.tsx
  src/locales/en/translation.json
  src/types/trading-pairs.ts
  yarn.lock
Labels: enhancement

#2184 fix(limit): failing limit order closing
  package.json
  src/app/components/Arbitrage/Arbitrage.tsx
  src/app/components/Form/ActionButton/index.tsx
  src/app/components/PairNavbarInfo/index.tsx
  src/app/components/RecentTrades/MarginTrades.tsx
  src/app/components/RecentTrades/RecentSwapRow.tsx
  src/app/components/RecentTrades/RecentTradeRow.tsx
  src/app/components/RecentTrades/SwapTrades.tsx
  src/app/components/RecentTrades/index.module.scss
  src/app/components/RecentTrades/index.tsx
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/index.tsx
  src/app/containers/SwapFormContainer/components/ReviewDialog/index.tsx
  src/app/containers/SwapFormContainer/components/SwapSelector/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/hooks/limitOrder/useLimitOrder.ts
  src/app/hooks/trading/useSwap_RecentTrades.ts
  src/app/hooks/useSendTx.ts
  src/app/pages/MarginTradePage/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/LiquidClaimForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
  src/app/pages/RewardPage/components/Tab/index.tsx
  src/app/pages/RewardPage/index.tsx
  src/locales/en/translation.json
  src/types/trading-pairs.ts
  yarn.lock
Labels: release, hotfix

#2145 Feat: Change colors
  src/app/containers/WalletConnector/index.tsx
  src/app/hooks/trading/useCachedAssetPrice.ts
  src/app/pages/BuySovPage/components/AmountButton/index.tsx
  src/app/pages/BuySovPage/components/Button/index.tsx
  src/app/pages/BuySovPage/components/BuyForm/Dialogs/TxDialog.tsx
  src/app/pages/BuySovPage/components/Card/index.tsx
  src/app/pages/BuySovPage/components/Feature/index.tsx
  src/app/pages/BuySovPage/components/Features/StakeVote.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/styled.ts
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/app/pages/PerpetualPage/components/ActionDialogSubmitButton/index.tsx
  src/app/pages/PerpetualPage/components/EditMarginDialog/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/components/ConnectFormStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/index.module.scss
  src/app/pages/PerpetualPage/components/TradingChart/index.tsx
  src/app/pages/RewardPage/components/Tab/index.module.scss
  src/app/pages/RewardPage/index.module.scss
  src/assets/images/confirm-tx.svg
  src/assets/images/error_outline-24px.svg
  src/assets/images/fast-btc/success-icon.svg
  src/assets/images/icon-success.svg
  src/assets/images/marginTrade/notifications_active_black_24dp.svg
  src/assets/images/settings-blue.svg
  tailwind.config.js
Labels: enhancement

#2159 Feat/2255707517 icon atomic component
  .storybook/webpack.config.js
  src/app/components/Icon/iconNames.ts
  src/app/components/Icon/iconSvgPaths.ts
  src/app/components/Icon/index.module.scss
  src/app/components/Icon/index.stories.tsx
  src/app/components/Icon/index.tsx
  src/app/components/Icon/types.ts
  src/app/components/Storybook/components/StorybookAnimatedBox.tsx
Labels: enhancement

#2161 [ACL] - contain fixes for frontend miscellaneous tasks
  src/app/components/AssetSymbolRenderer/index.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/index.module.scss
  src/locales/en/translation.json
  src/utils/dictionaries/assets-dictionary.ts
Labels: enhancement

#2181 [Spot] - add ids
  src/app/components/PairNavbar/Pair.tsx
  src/app/components/PairNavbar/PairCryptocurrency.tsx
  src/app/components/PairNavbar/PairSelect.tsx
  src/app/components/PairNavbar/index.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderSetting/Duration.tsx
  src/app/pages/SpotTradingPage/components/LimitOrderTables/LimitOrderRow.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/LimitForm.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/MarketForm.tsx
  src/app/pages/SpotTradingPage/index.tsx
Labels: enhancement

#2139 fix: use timestampToLockDate value instead of current timestamp to calculate voting power
  src/app/containers/StakePage/components/CurrentStakes.tsx
  src/app/containers/StakePage/components/DelegateForm.tsx
  src/app/containers/StakePage/index.tsx
  src/app/hooks/staking/useStaking_timestampToLockDate.ts
Labels: bug

#2151 feat: universal dialog component
  src/app/components/Dialog/index.module.scss
  src/app/components/Dialog/index.stories.tsx
  src/app/components/Dialog/index.tsx
  src/app/components/Dialog/types.ts
  src/app/components/Overlay/index.tsx
  src/app/components/Portal/index.tsx
Labels: enhancement

#2182 Perpetuals - Whitelisting
  src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceCard/index.tsx
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/components/TradeFormStep.tsx
  src/app/pages/PerpetualPage/hooks/usePerpetual_isAddressWhitelisted.ts
  src/app/pages/PerpetualPage/slice.ts
  src/app/pages/PerpetualPage/types.ts
  src/locales/en/translation.json
Labels: enhancement

#2185 Fix perpetual toasts
  src/app/index.tsx
  src/app/pages/PerpetualPage/components/CustomToastContent/index.tsx
  src/index.tsx
Labels: bug

#2138 feat: change TxDialogs with TransactionDialog
  src/app/components/Dialogs/StatusComponent.tsx
  src/app/components/Dialogs/TxDialog.module.scss
  src/app/components/Dialogs/TxDialog.tsx
  src/app/components/TransactionDialog/index.tsx
  src/app/components/UserAssets/UnWrapDialog.tsx
  src/app/components/UserAssets/Vesting/VestingWithdrawForm.tsx
  src/app/containers/StakePage/components/FeeBlock.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/pages/BuySovPage/components/BuyForm/Dialogs/TxDialog.tsx
  src/app/pages/BuySovPage/components/BuyForm/index.tsx
  src/app/pages/FastBtcPage/components/Deposit/SignatureValidation/index.tsx
  src/app/pages/FastBtcPage/components/Deposit/StatusScreen.tsx
  src/app/pages/FastBtcPage/components/Withdraw/StatusScreen.tsx
  src/app/pages/LendingPage/components/LendingDialog/index.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/AddLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/index.tsx
  src/app/pages/LiquidityMining/components/AmmPoolsBanner/AmmPool.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/RemoveLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/index.tsx
  src/app/pages/MarginTradePage/components/ClosePositionDialog/DialogContent.tsx
  src/app/pages/OriginsClaimPage/components/ClaimForm/index.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/BuyStep/components/BuyDialog/components/BuySection/index.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/TradeSummary.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/TransactionStep.tsx
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/LockedBalance.tsx
Labels: refactoring

#2189 Fix/recent trades loading fix
  src/app/components/RecentTrades/MarginTrades.tsx
  src/app/components/RecentTrades/SwapTrades.tsx
  src/app/hooks/trading/useMargin_RecentTrades.ts
  src/app/hooks/trading/useSwap_RecentTrades.ts
Labels: enhancement, hotfix

#2132 Feat/borrow collateral
  src/app/components/ActiveBorrowTable/index.tsx
  src/app/containers/WalletProvider/saga.ts
  src/app/hooks/useCacheCall.ts
  src/app/hooks/useEstimateGas.ts
  src/app/pages/BorrowPage/components/AddCollateralModal/AddCollateralHandler.tsx
  src/app/pages/BorrowPage/components/AddCollateralModal/AddCollateralModal.tsx
  src/app/pages/BorrowPage/components/AddCollateralModal/CollateralForm.tsx
  src/app/pages/BorrowPage/components/AddCollateralModal/ReviewStep.tsx
  src/app/pages/BorrowPage/components/AddCollateralModal/utils.ts
  src/app/pages/BorrowPage/hooks/useAddCollateralToBorrow.ts
  src/app/pages/BorrowPage/index.tsx
  src/app/pages/BorrowPage/slice.ts
  src/app/pages/BorrowPage/types.ts
  src/app/pages/MarginTradePage/components/TxFeeCalculator/TransactionFee.tsx
  src/app/pages/MarginTradePage/components/TxFeeCalculator/index.tsx
  src/locales/en/translation.json
  src/utils/blockchain/abi/FeeSharingProxy.json
  src/utils/sovryn/sovryn-network.ts
Labels: enhancement

#2051 Feat/intercom
  public/index.html
  src/app/containers/WalletProvider/index.tsx
  src/utils/intercom.ts
Labels: enhancement

#2191 [YieldFarm] - add data ids
  src/app/components/FinanceV2Components/LootDrop/index.tsx
  src/app/components/Form/AmountInput/index.tsx
  src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
  src/app/pages/LiquidityMining/components/AddLiquidityDialog/AddLiquidityDialogV1.tsx
  src/app/pages/LiquidityMining/components/MiningPool/index.tsx
  src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/RemoveLiquidityDialogV1.tsx
Labels: enhancement

#2190 Feat/2382474482 perps trade dialog adjustments
  package.json
  src/app/containers/WalletProvider/saga.ts
  src/app/pages/PerpetualPage/components/ClosePositionDialog/components/TradeFormStep.tsx
  src/app/pages/PerpetualPage/components/EditLeverageDialog/index.tsx
  src/app/pages/PerpetualPage/components/EditMarginDialog/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/types.tsx
  src/app/pages/PerpetualPage/components/OpenOrdersTable/components/OpenOrderRow.tsx
  src/app/pages/PerpetualPage/components/OpenPositionsTable/components/OpenPositionRow.tsx
  src/app/pages/PerpetualPage/components/PairSelector/PairSelectorButton.tsx
  src/app/pages/PerpetualPage/components/ToastsWatcher/components/ToastAdditionalInfo.tsx/index.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ApprovalStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ConfirmationStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ResultPosition.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ReviewStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/TradeSummary.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/TransactionStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/index.module.scss
  src/app/pages/PerpetualPage/components/TradeDialog/index.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/types.tsx
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
  src/app/pages/PerpetualPage/contexts/PerpetualQueriesContext.tsx
  src/app/pages/PerpetualPage/hooks/usePerpetual_OpenOrders.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_completedTransactions.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_depositMarginToken.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_executeTransaction.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_openTrade.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_transaction.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_withdrawAll.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_withdrawMarginToken.ts
  src/app/pages/PerpetualPage/types.ts
  src/app/pages/PerpetualPage/utils/contractUtils.tsx
  src/app/pages/PerpetualPage/utils/perpUtils.ts
  src/locales/en/translation.json
  src/store/global/transactions-store/types.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/blockchain/contracts.ts
  src/utils/classifiers.ts
  src/utils/dictionaries/perpetual-pair-dictionary.ts
  src/utils/models/perpetual-pair.ts
  yarn.lock
Labels: enhancement

#2197 [Stake] - add data ids for fees withdraw btn
  src/app/containers/StakePage/components/FeeBlock.tsx
  src/app/containers/StakePage/index.tsx
Labels: enhancement

#2200 hotfix: increase gas limit for repaying loans
  src/app/containers/RepayPositionHandler/RepayPositionForm.tsx
  src/app/containers/RepayPositionHandler/index.tsx
  src/app/hooks/useAssetBalanceOf.ts
  src/app/hooks/useBalance.ts
  src/utils/classifiers.ts
Labels: hotfix

#2163 Feat/2426099128 menu enforcement
  package.json
  src/app/components/Form/AssetSelect/index.tsx
  src/app/components/Form/AssetSelect/renderers.tsx
  src/app/components/Form/Select/index.tsx
  src/app/components/Form/Select/renderers.tsx
  src/app/components/Form/Select/types.ts
  src/app/components/Form/Select1/arrow-down.svg
  src/app/components/Form/Select1/index.module.scss
  src/app/components/Form/Select1/index.tsx
  src/app/components/Form/Select1/renderers.tsx
  src/app/components/Form/Select1/types.ts
  src/app/components/FormSelect/index.tsx
  src/app/components/Menu/components/MenuItem/index.module.scss
  src/app/components/PageHeader/index.tsx
  src/app/components/StakingDateSelector/index.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/index.module.scss
  src/app/containers/WalletConnector/index.tsx
  src/utils/blockchain/abi/FeeSharingProxy.json
  yarn.lock
Labels: enhancement

#2208 fix: storybook not building
  .storybook/webpack.config.js
Labels: bug

#2213 feat: enable margin limit orders
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/app/pages/MarginTradePage/index.tsx
Labels: release, hotfix

#2205 Fix: axios.get missing catch calls
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/hooks/trading/useSwap_RecentTrades.ts
  src/app/pages/MarginTradePage/components/NotificationSettingsDialog/index.tsx
  src/app/pages/SpotTradingPage/components/PriceHistory/index.tsx
Labels: bug

#2212 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2220 feat: update LM reward promos
  src/app/pages/LandingPage/components/Promotions/index.tsx
  src/app/pages/LiquidityMining/index.tsx
Labels: enhancement, release

#2216 feat: bump gaslimit for vest withdrawals
  src/utils/classifiers.ts
Labels: enhancement, hotfix

#2204 [MarginPage] update data-action-ids
  src/app/components/PairNavbar/PairCryptocurrency.tsx
  src/app/components/PairNavbar/PairSelect.tsx
  src/app/components/PairNavbar/index.tsx
  src/app/pages/MarginTradePage/components/LimitOrder/LimitOrderRow/index.tsx
  src/app/pages/MarginTradePage/components/OpenPositionsTable/PositionRow.tsx
Labels: enhancement

#2217 Feat perps adjust leverage handling
  package.json
  src/app/pages/BridgeDepositPage/dictionaries/bridge-network-dictionary.ts
  src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
  src/app/pages/PerpetualPage/components/ClosePositionDialog/components/SlippageFormStep.tsx
  src/app/pages/PerpetualPage/components/ClosePositionDialog/components/TradeFormStep.tsx
  src/app/pages/PerpetualPage/components/ClosePositionDialog/utils.tsx
  src/app/pages/PerpetualPage/components/EditLeverageDialog/index.tsx
  src/app/pages/PerpetualPage/components/EditMarginDialog/index.tsx
  src/app/pages/PerpetualPage/components/LeverageSelector/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/components/SlippageFormStep.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/components/TradeFormStep.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
  src/app/pages/PerpetualPage/components/NewPositionCard/types.tsx
  src/app/pages/PerpetualPage/components/OpenOrdersTable/components/OpenOrderRow.tsx
  src/app/pages/PerpetualPage/components/OpenPositionsTable/components/OpenPositionRow.tsx
  src/app/pages/PerpetualPage/components/TableRowAction/index.tsx
  src/app/pages/PerpetualPage/components/ToastsWatcher/components/ToastAdditionalInfo.tsx/index.tsx
  src/app/pages/PerpetualPage/components/ToastsWatcher/index.tsx
  src/app/pages/PerpetualPage/components/TradeDetails/index.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ApprovalStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ResultPosition.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/ReviewStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/TradeSummary.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/components/TransactionStep.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/index.tsx
  src/app/pages/PerpetualPage/components/TradeDialog/types.tsx
  src/app/pages/PerpetualPage/components/TradeForm/components/ResultingPosition.tsx
  src/app/pages/PerpetualPage/components/TradeForm/index.tsx
  src/app/pages/PerpetualPage/components/ValidationHint/ValidationHint.tsx
  src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
  src/app/pages/PerpetualPage/hooks/usePerpetual_ClosedPositions.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_OpenPositions.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_analyseTrade.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_calculateResultingPosition.ts
  src/app/pages/PerpetualPage/hooks/usePerpetual_transaction.ts
  src/app/pages/PerpetualPage/types.ts
  src/app/pages/PerpetualPage/utils/contractUtils.tsx
  src/app/pages/PerpetualPage/utils/perpUtils.ts
  yarn.lock
Labels: enhancement

#2202 [BorrowPage] add data-action-ids
  src/app/components/FormSelect/index.tsx
  src/app/pages/BorrowPage/BorrowingContainer/index.tsx
  src/app/pages/BorrowPage/components/CurrencyContainer/CurrencyRow.tsx
Labels: enhancement

#2207 [New] Header menu refactoring
  src/app/components/Menu/components/MenuItem/index.module.scss
  src/app/components/Menu/components/MenuItem/index.tsx
  src/app/components/PairNavbar/index.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/index.module.scss
  src/app/containers/WalletConnector/index.module.scss
  src/app/containers/WalletConnector/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement

#2226 New strings PT-BR
  src/locales/pt_br/translation.json
Labels: copy

#2228 [Stake] - add data ids
  src/app/components/Menu/components/MenuItem/index.tsx
  src/app/components/StakingDateSelector/CustomArrow.tsx
  src/app/components/StakingDateSelector/CustomButtonGroup.tsx
  src/app/components/StakingDateSelector/index.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/containers/StakePage/components/DelegateForm.tsx
  src/app/containers/StakePage/components/ExtendStakeForm.tsx
  src/app/containers/StakePage/components/IncreaseStakeForm.tsx
  src/app/containers/StakePage/components/StakeForm.tsx
  src/app/containers/StakePage/components/WithdrawForm.tsx
  src/app/containers/StakePage/components/WithdrawVesting.tsx
Labels: enhancement
