Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2023-05, with the labels that each got.

#2527 SOV-2023: Show maximum price
  src/app/containers/SwapFormContainer/components/ReviewDialog/index.tsx
  src/app/containers/SwapFormContainer/index.tsx
  src/app/pages/BuySovPage/components/BuyForm/Dialogs/SlippageDialog.tsx
  src/app/pages/SpotTradingPage/components/TradeDialog/index.tsx
  src/app/pages/SpotTradingPage/components/TradeForm/MarketForm.tsx
  src/locales/en/translation.json
Labels: enhancement

#2526 SOV-1811: Fix XUSD and DOC regression
  src/app/components/PairNavbarInfo/index.tsx
Labels: bug

#2524 SOV-2243: restore Mynt link in Header menu
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/utils/classifiers.ts
Labels: enhancement, do-not-merge!
