Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2023-06, with the labels that each got.

#2546 SOV-2488: update maxCheckpoints for fee claiming
  src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
Labels: enhancement

#2547 SOV-2472: bump gas limit for Staking withdrawals
  src/utils/classifiers.ts
Labels: enhancement

#2550 SOV-2530/SOV-2529: Vesting & Reward Claiming updates
  src/app/components/UserAssets/Vesting/VestingWithdrawForm.tsx
  src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
  src/store/global/transactions-store/types.ts
  src/utils/classifiers.ts
Labels: enhancement

#2549 SOV-2463: remove storybook
  .env.testnet
  .eslintrc.js
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  .storybook/webpack.config.js
  README.md
  netlify.toml
  package.json
  src/app/components/Button/index.stories.tsx
  src/app/components/Checkbox/index.stories.tsx
  src/app/components/Dialog/index.stories.tsx
  src/app/components/Dropdown/index.stories.tsx
  src/app/components/FormGroup/index.stories.tsx
  src/app/components/Heading/index.stories.tsx
  src/app/components/Icon/index.stories.tsx
  src/app/components/Input/index.stories.tsx
  src/app/components/Menu/index.stories.tsx
  src/app/components/Overlay/index.stories.tsx
  src/app/components/Pagination/index.stories.tsx
  src/app/components/Picture/index.stories.tsx
  src/app/components/RadioButton/index.stories.tsx
  src/app/components/Spinner/index.stories.tsx
  src/app/components/Storybook/animations.stories.tsx
  src/app/components/Storybook/borders.stories.tsx
  src/app/components/Storybook/colors.stories.tsx
  src/app/components/Storybook/components/StorybookAnimatedBox.tsx
  src/app/components/Storybook/components/StorybookSwatch.tsx
  src/app/components/Storybook/components/StorybookTailwindUsage.tsx
  src/app/components/Storybook/components/StorybookTextSample.tsx
  src/app/components/Storybook/sizes.stories.tsx
  src/app/components/Storybook/text.stories.tsx
  src/app/components/Storybook/transitions.stories.tsx
  src/app/components/Switch/index.stories.tsx
  src/app/components/Table/index.stories.tsx
  src/app/components/Tabs/index.stories.tsx
  src/app/containers/TransitionContainer/index.stories.tsx
  src/app/containers/TransitionSteps/index.stories.tsx
  src/styles/sass/global.scss
  yarn.lock
Labels: refactoring

#2552 SOV-2632: bump sovryn/react-wallet version
  package.json
  yarn.lock
Labels: dependencies

#2557 SOV-2671: update Discord link in footer
  CONTRIBUTING.md
  README.md
  src/utils/classifiers.ts
Labels: enhancement

#2548 SOV-2453: Use getAccumulatedFeesForCheckpointsRange instead of getAccumulatedFees
  src/app/constants.ts
  src/app/containers/StakePage/components/FeeBlock.tsx
  src/app/hooks/staking/useStaking_getAccumulatedFees.ts
  src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
  src/app/pages/RewardPage/hooks/useGetFeesEarned.ts
  src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
  src/app/pages/RewardPage/hooks/useGetTokenCheckpoints.ts
  src/utils/blockchain/abi/FeeSharingProxy.json
  src/utils/helpers.ts
Labels: enhancement

#2556 SOV-2634: remove WalletConnect
  package.json
  src/app/components/TransactionDialog/utils.ts
  src/app/components/UserAssets/TxDialog/WalletLogo.tsx
  src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/BuyStep/components/BuyDialog/components/TxDialog/WalletLogo.tsx
  src/assets/wallets/walletconnect.svg
  src/utils/helpers.ts
  yarn.lock
Labels: enhancement

#2553 SOV-2532: add title to sovryn.app menu
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement
