Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2023-02, with the labels that each got.

#2478 SOV-1764 add dllr to spot trading pairs
  src/app/pages/SpotTradingPage/types.ts
Labels: enhancement

#2483 SOV-1897: Increase Liquid SOV claim gaslimit
  src/utils/classifiers.ts
Labels: enhancement, hotfix

#2486 SOV-1903: Reward SOV claiming using stakingRewardsProxy contract balance check
  src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/LiquidClaimForm/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
Labels: bug, hotfix
