Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2023-03, with the labels that each got.

#2485 SOV-1865: Added subscription payload to notifications
  src/app/pages/MarginTradePage/components/NotificationSettingsDialog/index.tsx
  src/app/pages/MarginTradePage/types.ts
Labels: enhancement

#2488 Pair Nav Data/Mynt
  src/app/components/Menu/components/MenuItem/index.module.scss
  src/app/components/PairNavbarInfo/index.tsx
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/hooks/trading/useGetCandlesData.ts
  src/types/trading-pairs.ts
Labels: bug, hotfix

#2481 SOV-1510: update rewards page
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/app/containers/WalletConnector/index.tsx
  src/app/index.tsx
  src/app/pages/PortfolioPage/index.tsx
  src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
  src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
  src/utils/blockchain/abi/FeeSharingProxy.json
Labels: enhancement

#2487 SOV-1810: DLLR the quote currency in the Spot trading
  src/app/pages/SpotTradingPage/types.ts
Labels: enhancement

#2490 SOV-1954: Pair Selector price change issue
  src/app/components/PairNavbar/utils.ts
  src/app/components/PairNavbarInfo/index.tsx
Labels: bug

#2489 SOV-1404: Use correct target token in cross chain deposit flow
  src/app/pages/BridgeDepositPage/components/ReviewStep/index.tsx
Labels: bug

#2492 SOV-1874: Lowercase user address
  src/app/containers/WalletConnector/index.tsx
Labels: enhancement

#2494 SOV-1751: Update VestingRegistry contract
  src/utils/blockchain/abi/VestingRegistry.json
Labels: enhancement

#2495 SOV-746: Fix email notification settings dialog
  src/app/containers/WalletProvider/slice.ts
  src/app/containers/WalletProvider/types.ts
  src/app/pages/MarginTradePage/components/NotificationSettingsDialog/index.tsx
  src/app/pages/MarginTradePage/slice.ts
  src/app/pages/MarginTradePage/types.ts
  src/utils/metamaskHelpers.ts
Labels: bug

#2493 SOV-1761: Fix Fast BTC information
  src/app/components/AddressBadge/index.tsx
  src/app/pages/FastBtcPage/components/Deposit/StatusScreen.tsx
  src/app/pages/FastBtcPage/containers/DepositContainer.tsx
  src/app/pages/FastBtcPage/contexts/deposit-context.ts
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getFastBtcDepositRskTransaction.graphql
  src/utils/graphql/rsk/schema.graphql
Labels: enhancement

#2491 SOV-1982: update "yield farming" banners
  src/app/pages/LiquidityMining/index.tsx
  src/locales/en/translation.json
  src/utils/dictionaries/amm/testnet.ts
Labels: enhancement

#2498 SOV-1711: add GTM clickthrough id
  .env.example
  .env.local
  .env.mainnet.local
  .env.testnet
  netlify.toml
  public/index.html
Labels: enhancement

#2499 SOV-1877: D1 DLLR integration
  src/utils/blockchain/contracts.ts
  src/utils/dictionaries/amm/mainnet.ts
Labels: enhancement

#2500 SOV-2038: Spot chart updates
  src/app/components/PairNavbar/index.tsx
  src/app/components/PairNavbarInfo/index.tsx
  src/app/components/TradingChart/datafeed.ts
  src/app/components/TradingChart/helpers.ts
  src/app/pages/SpotTradingPage/types.ts
  src/types/trading-pairs.ts
Labels: bug

#2504 SOV-1841: final dapp cleanup
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
  src/assets/images/banner/Zero_banner.svg
  src/assets/images/banner/Zero_banner_mobile.svg
  src/utils/classifiers.ts
Labels: enhancement

#2505 Fix/spot
  src/app/components/PairNavbarInfo/index.tsx
  src/app/components/TradingChart/datafeed.ts
  src/app/components/TradingChart/helpers.ts
  src/app/components/TradingChart/streaming.ts
Labels: bug

#2507 Yield Farm Refactoring
  src/app/components/Promotions/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/locales/pt_br/translation.json
  src/utils/dictionaries/amm/mainnet.ts
  src/utils/dictionaries/amm/testnet.ts
Labels: bug, enhancement

#2508 SOV-1867: Fix margin long slippage form
  src/app/hooks/trading/useTrading_resolvePairTokens.ts
  src/app/hooks/useCacheCall.ts
  src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
  src/app/pages/MarginTradePage/components/SlippageForm/index.tsx
  src/app/pages/MarginTradePage/components/TradeForm/index.tsx
  src/app/pages/MarginTradePage/utils/marginUtils.ts
  src/locales/en/translation.json
Labels: enhancement

#2497 Translations update from Hosted Weblate
  src/locales/pt/translation.json
  src/locales/pt_br/translation.json
Labels: copy

#2511 SOV-2140: bump gaslimit for claiming RBTC fees
  src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
  src/store/global/transactions-store/types.ts
  src/utils/classifiers.ts
Labels: enhancement

#2510 SOV-1606: fix ugly liquality error message
  src/app/components/TransactionDialog/TxRequestDialog.tsx
  src/app/components/TransactionDialog/hooks/useGetNormalizedError.ts
  src/app/components/TransactionDialog/index.tsx
  src/locales/en/translation.json
Labels: bug

#2512 SOV-2001: Update reward SOV page
  src/app/pages/RewardPage/components/FeesEarnedTab/index.tsx
  src/app/pages/RewardPage/components/HistoryTable/index.tsx
  src/app/pages/RewardPage/components/LiquidTab/index.tsx
  src/app/pages/RewardPage/components/RewardTab/hooks/useGetAvailableLiquidityRewards.ts
  src/app/pages/RewardPage/components/RewardTab/index.tsx
  src/app/pages/RewardPage/components/RewardsDetail/index.tsx
  src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
  src/app/pages/RewardPage/hooks/useGetUserRewardsEarnedHistory.ts
  src/app/pages/RewardPage/index.tsx
  src/locales/en/translation.json
  src/locales/pt_br/translation.json
  src/utils/blockchain/abi/LiquidityMining.json
  src/utils/graphql/rsk/generated.tsx
  src/utils/graphql/rsk/operations/getUserRewardsEarnedHistory.graphql
Labels: enhancement
