Repository DistributedCollective/Sovryn-frontend, pull requests merged in 2023-04, with the labels that each got.

#2514 fix: safari crashing because of unsupported regex
  src/app/components/TransactionDialog/hooks/useGetNormalizedError.ts
Labels: bug, hotfix

#2516 SOV-2021: update Promo cards display
  src/app/components/Promotions/components/PromotionCard/index.module.scss
  src/app/components/Promotions/components/PromotionCard/index.tsx
  src/app/components/Promotions/components/PromotionCard/utils.tsx
  src/app/components/Promotions/index.tsx
  src/app/pages/LiquidityMining/index.tsx
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/locales/pt/translation.json
  src/locales/pt_br/translation.json
Labels: enhancement

#2519 SOV-2160: DLLR Lend pool, use DLLR as collateral
  src/app/components/FinanceV2Components/utils/getAssetColor.ts
  src/app/hooks/lending/useGetLendingHistory.ts
  src/utils/blockchain/contracts.testnet.ts
  src/utils/dictionaries/lending-pool-dictionary.ts
Labels: enhancement

#2521 SOV-2250: update reward SOV promo amounts and recalibration date
  src/app/pages/LiquidityMining/index.tsx
  src/locales/en/translation.json
  src/locales/pt/translation.json
  src/locales/pt_br/translation.json
  src/utils/dateHelpers.ts
Labels: enhancement, hotfix

#2517 SOV-2028: Enforce Babelfish Aggregator pause state for tokens on Bridge
  .env.local
  .env.mainnet.local
  .env.production
  .env.testnet
  codegen.fetch.yml
  codegen.yml
  netlify.toml
  src/app/pages/BridgeDepositPage/components/TokenSelector/TokenItem.tsx
  src/app/pages/BridgeDepositPage/components/TokenSelector/index.tsx
  src/app/pages/BridgeDepositPage/hooks/useGetPausedTokens.ts
  src/index.tsx
  src/utils/classifiers.ts
  src/utils/clients.ts
  src/utils/graphql/babelfish/generated.tsx
  src/utils/graphql/babelfish/operations/getPausedBassetList.graphql
  src/utils/graphql/babelfish/schema.graphql
Labels: enhancement

#2529 SOV-2310: prevent internal redirect for external links on mobile header menu
  src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
Labels: bug
